create table products (
	id SERIAL PRIMARY KEY NOT NULL,
	name VARCHAR(50),
	brand VARCHAR(20),
	price INTEGER
);


insert into products (id, name, brand, price) values (1, 'Macaroons - Two Bite Choc', 'Zoomcast', 41);
insert into products (id, name, brand, price) values (2, 'Broom And Brush Rack Black', 'Jabberstorm', 34);
insert into products (id, name, brand, price) values (3, 'Ranchero - Primerba, Paste', 'Jabbersphere', 53);
insert into products (id, name, brand, price) values (4, 'Jack Daniels', 'Twinte', 69);
insert into products (id, name, brand, price) values (5, 'Straws - Cocktale', 'Rhycero', 19);
insert into products (id, name, brand, price) values (6, 'Nut - Cashews, Whole, Raw', 'Thoughtworks', 31);
insert into products (id, name, brand, price) values (7, 'Sprouts Dikon', 'Thoughtsphere', 33);
insert into products (id, name, brand, price) values (8, 'Mountain Dew', 'Browseblab', 67);
insert into products (id, name, brand, price) values (9, 'Miso - Soy Bean Paste', 'Buzzbean', 78);
insert into products (id, name, brand, price) values (10, 'Beef - Bresaola', 'Realcube', 73);
insert into products (id, name, brand, price) values (11, 'Filo Dough', 'Avaveo', 21);
insert into products (id, name, brand, price) values (12, 'Wiberg Cure', 'Gabtune', 41);
insert into products (id, name, brand, price) values (13, 'Wine - White, Pelee Island', 'Topicware', 47);
insert into products (id, name, brand, price) values (14, 'Figs', 'Twimm', 32);
insert into products (id, name, brand, price) values (15, 'Tea - Jasmin Green', 'Blogtag', 20);
insert into products (id, name, brand, price) values (16, 'Container - Hngd Cll Blk 7x7x3', 'Gigabox', 9);
insert into products (id, name, brand, price) values (17, 'Gloves - Goldtouch Disposable', 'JumpXS', 62);
insert into products (id, name, brand, price) values (18, 'Filo Dough', 'Mybuzz', 51);
insert into products (id, name, brand, price) values (19, 'Bar - Sweet And Salty Chocolate', 'Oyonder', 80);
insert into products (id, name, brand, price) values (20, 'Cheese - Goat With Herbs', 'Jabbertype', 17);
insert into products (id, name, brand, price) values (21, 'Bread - White, Sliced', 'Brightbean', 83);
insert into products (id, name, brand, price) values (22, 'Nantucket - Pomegranate Pear', 'Jaloo', 41);
insert into products (id, name, brand, price) values (23, 'Shrimp - Black Tiger 13/15', 'Youfeed', 29);
insert into products (id, name, brand, price) values (24, 'Pasta - Ravioli', 'Feedspan', 48);
insert into products (id, name, brand, price) values (25, 'Blouse / Shirt / Sweater', 'Fliptune', 66);
insert into products (id, name, brand, price) values (26, 'Ginsing - Fresh', 'Vipe', 79);
insert into products (id, name, brand, price) values (27, 'Juice - Apple, 341 Ml', 'Oba', 36);
insert into products (id, name, brand, price) values (28, 'Bagelers', 'Chatterpoint', 36);
insert into products (id, name, brand, price) values (29, 'Milk - Buttermilk', 'Livetube', 29);
insert into products (id, name, brand, price) values (30, 'Cocoa Powder - Dutched', 'Ooba', 77);
insert into products (id, name, brand, price) values (31, 'Lotus Root', 'Rhynoodle', 21);
insert into products (id, name, brand, price) values (32, 'Milk - Buttermilk', 'Snaptags', 16);
insert into products (id, name, brand, price) values (33, 'Wine - Zonnebloem Pinotage', 'Yakidoo', 94);
insert into products (id, name, brand, price) values (34, 'Fond - Neutral', 'Trudeo', 21);
insert into products (id, name, brand, price) values (35, 'Juice - Orange, Concentrate', 'Tekfly', 31);
insert into products (id, name, brand, price) values (36, 'Wine - Saint - Bris 2002, Sauv', 'Innojam', 96);
insert into products (id, name, brand, price) values (37, 'Pork - Smoked Back Bacon', 'Rhybox', 60);
insert into products (id, name, brand, price) values (38, 'Soup - Campbells, Creamy', 'Aivee', 97);
insert into products (id, name, brand, price) values (39, 'Gelatine Powder', 'Linklinks', 99);
insert into products (id, name, brand, price) values (40, 'Lid Coffeecup 12oz D9542b', 'Flashspan', 3);
insert into products (id, name, brand, price) values (41, 'Flavouring - Raspberry', 'Edgetag', 78);
insert into products (id, name, brand, price) values (42, 'Coconut - Shredded, Sweet', 'Jayo', 5);
insert into products (id, name, brand, price) values (43, 'Glass - Juice Clear 5oz 55005', 'Mudo', 80);
insert into products (id, name, brand, price) values (44, 'Red Currants', 'Thoughtstorm', 9);
insert into products (id, name, brand, price) values (45, 'Peach - Fresh', 'Vinte', 13);
insert into products (id, name, brand, price) values (46, 'Wine - White, Ej', 'Quaxo', 22);
insert into products (id, name, brand, price) values (47, 'Tea - Herbal I Love Lemon', 'Livetube', 38);
insert into products (id, name, brand, price) values (48, 'Broom - Push', 'Kwilith', 25);
insert into products (id, name, brand, price) values (49, 'Garlic - Peeled', 'Yodel', 5);
insert into products (id, name, brand, price) values (50, 'Wine - Placido Pinot Grigo', 'Devify', 80);
insert into products (id, name, brand, price) values (51, 'Chickhen - Chicken Phyllo', 'Twinte', 92);
insert into products (id, name, brand, price) values (52, 'Sausage - Blood Pudding', 'Feedmix', 75);
insert into products (id, name, brand, price) values (53, 'Pepper - Cayenne', 'Babbleblab', 56);
insert into products (id, name, brand, price) values (54, 'Beef Ground Medium', 'Yakidoo', 97);
insert into products (id, name, brand, price) values (55, 'Veal - Ground', 'Quire', 12);
insert into products (id, name, brand, price) values (56, 'Water - Spring Water, 355 Ml', 'Wordtune', 1);
insert into products (id, name, brand, price) values (57, 'Beef - Diced', 'Twitternation', 66);
insert into products (id, name, brand, price) values (58, 'Anchovy In Oil', 'Thoughtmix', 30);
insert into products (id, name, brand, price) values (59, 'Pasta - Fett Alfredo, Single Serve', 'Jabbercube', 45);
insert into products (id, name, brand, price) values (60, 'Fish - Halibut, Cold Smoked', 'Izio', 58);
insert into products (id, name, brand, price) values (61, 'Flour - Buckwheat, Dark', 'Vimbo', 16);
insert into products (id, name, brand, price) values (62, 'Pork - Loin, Boneless', 'Riffwire', 91);
insert into products (id, name, brand, price) values (63, 'Bacardi Raspberry', 'Thoughtstorm', 34);
insert into products (id, name, brand, price) values (64, 'Glucose', 'Topicblab', 6);
insert into products (id, name, brand, price) values (65, 'Wine - Red, Cabernet Sauvignon', 'Abatz', 87);
insert into products (id, name, brand, price) values (66, 'Scallops - 20/30', 'Quatz', 88);
insert into products (id, name, brand, price) values (67, 'Cheese - Marble', 'Zoozzy', 98);
insert into products (id, name, brand, price) values (68, 'Parsley - Fresh', 'Lazz', 54);
insert into products (id, name, brand, price) values (69, 'Stock - Veal, Brown', 'Meejo', 78);
insert into products (id, name, brand, price) values (70, 'Maintenance Removal Charge', 'Centizu', 27);
insert into products (id, name, brand, price) values (71, 'Towels - Paper / Kraft', 'Riffpath', 10);
insert into products (id, name, brand, price) values (72, 'Tofu - Soft', 'Kazio', 36);
insert into products (id, name, brand, price) values (73, 'Pasta - Ravioli', 'Twitterworks', 73);
insert into products (id, name, brand, price) values (74, 'Beef - Striploin Aa', 'Devcast', 78);
insert into products (id, name, brand, price) values (75, 'Kumquat', 'Edgetag', 22);
insert into products (id, name, brand, price) values (76, 'Sugar - Brown', 'Eazzy', 87);
insert into products (id, name, brand, price) values (77, 'Juice - Cranberry 284ml', 'Kaymbo', 70);
insert into products (id, name, brand, price) values (78, 'Chocolate - Milk, Callets', 'Feedmix', 60);
insert into products (id, name, brand, price) values (79, 'Transfer Sheets', 'Katz', 28);
insert into products (id, name, brand, price) values (80, 'Tomato - Peeled Italian Canned', 'Photolist', 54);
insert into products (id, name, brand, price) values (81, 'Bread - Bagels, Plain', 'Agivu', 82);
insert into products (id, name, brand, price) values (82, 'Oyster - In Shell', 'Ntags', 66);
insert into products (id, name, brand, price) values (83, 'Icecream - Dstk Strw Chseck', 'Trilith', 39);
insert into products (id, name, brand, price) values (84, 'Sausage - Blood Pudding', 'Voolith', 21);
insert into products (id, name, brand, price) values (85, 'Radish', 'Ntag', 42);
insert into products (id, name, brand, price) values (86, 'Wine - Charddonnay Errazuriz', 'Kwinu', 1);
insert into products (id, name, brand, price) values (87, 'Towel - Roll White', 'Twitterwire', 51);
insert into products (id, name, brand, price) values (88, 'Bread - Hamburger Buns', 'Eidel', 2);
insert into products (id, name, brand, price) values (89, 'Pasta - Penne, Rigate, Dry', 'Shuffledrive', 56);
insert into products (id, name, brand, price) values (90, 'Bread - Hamburger Buns', 'Feedmix', 68);
insert into products (id, name, brand, price) values (91, 'Guinea Fowl', 'Flashpoint', 23);
insert into products (id, name, brand, price) values (92, 'Pasta - Agnolotti - Butternut', 'Twitterworks', 93);
insert into products (id, name, brand, price) values (93, 'Oil - Grapeseed Oil', 'Twimbo', 87);
insert into products (id, name, brand, price) values (94, 'Campari', 'Topicblab', 15);
insert into products (id, name, brand, price) values (95, 'Pumpkin', 'Livetube', 53);
insert into products (id, name, brand, price) values (96, 'Wine - Remy Pannier Rose', 'Zoovu', 97);
insert into products (id, name, brand, price) values (97, 'Juice - Apple, 341 Ml', 'Kwinu', 34);
insert into products (id, name, brand, price) values (98, 'Mushroom - White Button', 'Jaxworks', 63);
insert into products (id, name, brand, price) values (99, 'Soho Lychee Liqueur', 'Meedoo', 72);
insert into products (id, name, brand, price) values (100, 'Longos - Cheese Tortellini', 'InnoZ', 24);
insert into products (id, name, brand, price) values (101, 'Pastry - Key Limepoppy Seed Tea', 'Camimbo', 10);
insert into products (id, name, brand, price) values (102, 'Sauce - Balsamic Viniagrette', 'Wordify', 19);
insert into products (id, name, brand, price) values (103, 'Cookies Cereal Nut', 'Kimia', 9);
insert into products (id, name, brand, price) values (104, 'Dc - Frozen Momji', 'Vimbo', 64);
insert into products (id, name, brand, price) values (105, 'Cheese - Wine', 'Browsetype', 62);
insert into products (id, name, brand, price) values (106, 'Carroway Seed', 'Jabberbean', 14);
insert into products (id, name, brand, price) values (107, 'Wine - Lou Black Shiraz', 'Mycat', 82);
insert into products (id, name, brand, price) values (108, 'Cake Slab', 'Izio', 26);
insert into products (id, name, brand, price) values (109, 'Pork - Suckling Pig', 'Shufflebeat', 40);
insert into products (id, name, brand, price) values (110, 'Halibut - Whole, Fresh', 'Babbleopia', 85);
insert into products (id, name, brand, price) values (111, 'Coffee - Cafe Moreno', 'Devshare', 91);
insert into products (id, name, brand, price) values (112, 'V8 - Tropical Blend', 'Oyoloo', 58);
insert into products (id, name, brand, price) values (113, 'Appetizer - Lobster Phyllo Roll', 'Yata', 59);
insert into products (id, name, brand, price) values (114, 'Bread - White, Sliced', 'Mudo', 70);
insert into products (id, name, brand, price) values (115, 'Appetizer - Mushroom Tart', 'Realcube', 86);
insert into products (id, name, brand, price) values (116, 'Wine - Red, Concha Y Toro', 'Devify', 22);
insert into products (id, name, brand, price) values (117, 'Rosemary - Dry', 'Zazio', 10);
insert into products (id, name, brand, price) values (118, 'Potatoes - Mini White 3 Oz', 'Einti', 80);
insert into products (id, name, brand, price) values (119, 'Rum - White, Gg White', 'Bluezoom', 64);
insert into products (id, name, brand, price) values (120, 'Oregano - Dry, Rubbed', 'Twimm', 86);
insert into products (id, name, brand, price) values (121, 'Wine - Chablis J Moreau Et Fils', 'Zooxo', 81);
insert into products (id, name, brand, price) values (122, 'Venison - Denver Leg Boneless', 'Leenti', 78);
insert into products (id, name, brand, price) values (123, 'Toamtoes 6x7 Select', 'Eadel', 89);
insert into products (id, name, brand, price) values (124, 'Oil - Olive', 'Kamba', 44);
insert into products (id, name, brand, price) values (125, 'Danishes - Mini Raspberry', 'Pixonyx', 42);
insert into products (id, name, brand, price) values (126, 'Cheese - Parmesan Grated', 'Snaptags', 58);
insert into products (id, name, brand, price) values (127, 'Bread - Ciabatta Buns', 'Mynte', 88);
insert into products (id, name, brand, price) values (128, 'Pork Loin Cutlets', 'Quinu', 85);
insert into products (id, name, brand, price) values (129, 'Dome Lid Clear P92008h', 'Devbug', 48);
insert into products (id, name, brand, price) values (130, 'Venison - Striploin', 'Photobug', 4);
insert into products (id, name, brand, price) values (131, 'Energy Drink Red Bull', 'Skivee', 67);
insert into products (id, name, brand, price) values (132, 'Pepper - Red Thai', 'Zoonoodle', 74);
insert into products (id, name, brand, price) values (133, 'Mushroom - Oyster, Fresh', 'Babbleblab', 56);
insert into products (id, name, brand, price) values (134, 'Cookie Chocolate Chip With', 'Oyoyo', 22);
insert into products (id, name, brand, price) values (135, 'Juice - Ocean Spray Cranberry', 'Realblab', 55);
insert into products (id, name, brand, price) values (136, 'Vodka - Hot, Lnferno', 'Realcube', 19);
insert into products (id, name, brand, price) values (137, 'Pasta - Lasagna Noodle, Frozen', 'Twitterbeat', 36);
insert into products (id, name, brand, price) values (138, 'Rabbit - Whole', 'Meevee', 83);
insert into products (id, name, brand, price) values (139, 'Fib N9 - Prague Powder', 'Browsezoom', 83);
insert into products (id, name, brand, price) values (140, 'Juice - Cranberry 284ml', 'Youopia', 99);
insert into products (id, name, brand, price) values (141, 'Crackers - Melba Toast', 'Flashset', 33);
insert into products (id, name, brand, price) values (142, 'Gelatine Powder', 'Miboo', 2);
insert into products (id, name, brand, price) values (143, 'Wine - Penfolds Koonuga Hill', 'Aibox', 53);
insert into products (id, name, brand, price) values (144, 'Towels - Paper / Kraft', 'Shufflebeat', 78);
insert into products (id, name, brand, price) values (145, 'Veal - Brisket, Provimi,bnls', 'Kwilith', 86);
insert into products (id, name, brand, price) values (146, 'Apple - Delicious, Golden', 'Ntags', 40);
insert into products (id, name, brand, price) values (147, 'Juice - Ocean Spray Kiwi', 'Layo', 19);
insert into products (id, name, brand, price) values (148, 'Oranges - Navel, 72', 'Yakidoo', 93);
insert into products (id, name, brand, price) values (149, 'Mortadella', 'Wikibox', 52);
insert into products (id, name, brand, price) values (150, 'Lettuce - Curly Endive', 'Oloo', 5);
insert into products (id, name, brand, price) values (151, 'Cake - Cake Sheet Macaroon', 'Eazzy', 12);
insert into products (id, name, brand, price) values (152, 'Plastic Wrap', 'Wikizz', 18);
insert into products (id, name, brand, price) values (153, 'Nut - Pumpkin Seeds', 'Yodel', 50);
insert into products (id, name, brand, price) values (154, 'Beef - Salted', 'Wikido', 47);
insert into products (id, name, brand, price) values (155, 'Soup - Verve - Chipotle Chicken', 'Twitterworks', 6);
insert into products (id, name, brand, price) values (156, 'Sugar - Monocystal / Rock', 'Brightbean', 50);
insert into products (id, name, brand, price) values (157, 'Ham - Cooked Italian', 'Kazio', 64);
insert into products (id, name, brand, price) values (158, 'Zucchini - Yellow', 'Vidoo', 3);
insert into products (id, name, brand, price) values (159, 'Magnotta - Bel Paese White', 'Wordtune', 19);
insert into products (id, name, brand, price) values (160, 'Muffin Hinge Container 6', 'Jayo', 65);
insert into products (id, name, brand, price) values (161, 'Spinach - Baby', 'Flashpoint', 71);
insert into products (id, name, brand, price) values (162, 'Wine - Niagara,vqa Reisling', 'Yakijo', 21);
insert into products (id, name, brand, price) values (163, 'Tomatoes - Roma', 'Kaymbo', 15);
insert into products (id, name, brand, price) values (164, 'Cranberries - Fresh', 'Gigaclub', 3);
insert into products (id, name, brand, price) values (165, 'Wine - Two Oceans Cabernet', 'Gigashots', 59);
insert into products (id, name, brand, price) values (166, 'Mini - Vol Au Vents', 'Trudoo', 89);
insert into products (id, name, brand, price) values (167, 'Juice - Apple, 1.36l', 'Kare', 26);
insert into products (id, name, brand, price) values (168, 'Crush - Orange, 355ml', 'Realfire', 63);
insert into products (id, name, brand, price) values (169, 'Wine - Barolo Fontanafredda', 'Yacero', 78);
insert into products (id, name, brand, price) values (170, 'Chocolate Bar - Smarties', 'Kayveo', 38);
insert into products (id, name, brand, price) values (171, 'Tea - Honey Green Tea', 'Camimbo', 6);
insert into products (id, name, brand, price) values (172, 'Sauce - Cranberry', 'Zoombeat', 27);
insert into products (id, name, brand, price) values (173, 'Truffle Cups - Brown', 'Dabtype', 76);
insert into products (id, name, brand, price) values (174, 'Tray - 16in Rnd Blk', 'Devpoint', 57);
insert into products (id, name, brand, price) values (175, 'Water - Green Tea Refresher', 'Yozio', 24);
insert into products (id, name, brand, price) values (176, 'Tea - English Breakfast', 'Devify', 2);
insert into products (id, name, brand, price) values (177, 'Tea - Earl Grey', 'Twimm', 64);
insert into products (id, name, brand, price) values (178, 'The Pop Shoppe - Grape', 'Bluezoom', 45);
insert into products (id, name, brand, price) values (179, 'Cardamon Seed / Pod', 'Twinder', 96);
insert into products (id, name, brand, price) values (180, 'Glaze - Apricot', 'Vinder', 81);
insert into products (id, name, brand, price) values (181, 'Wiberg Cure', 'Avamba', 50);
insert into products (id, name, brand, price) values (182, 'Wine - Pinot Noir Stoneleigh', 'Divape', 58);
insert into products (id, name, brand, price) values (183, 'Salmon - Sockeye Raw', 'Roodel', 30);
insert into products (id, name, brand, price) values (184, 'Asparagus - Green, Fresh', 'Jabberstorm', 61);
insert into products (id, name, brand, price) values (185, 'Nut - Almond, Blanched, Sliced', 'Skimia', 17);
insert into products (id, name, brand, price) values (186, 'Ginger - Ground', 'Centidel', 69);
insert into products (id, name, brand, price) values (187, 'Cake - Sheet Strawberry', 'Wikido', 60);
insert into products (id, name, brand, price) values (188, 'Soup - Campbells - Tomato', 'Topicware', 5);
insert into products (id, name, brand, price) values (189, 'Wine - Segura Viudas Aria Brut', 'Eimbee', 54);
insert into products (id, name, brand, price) values (190, 'Bread - Pita, Mini', 'Quamba', 1);
insert into products (id, name, brand, price) values (191, 'Beer - Alexander Kieths, Pale Ale', 'Twitternation', 18);
insert into products (id, name, brand, price) values (192, 'Salt - Kosher', 'Tagcat', 11);
insert into products (id, name, brand, price) values (193, 'French Kiss Vanilla', 'Rhyloo', 93);
insert into products (id, name, brand, price) values (194, 'Vol Au Vents', 'Agivu', 5);
insert into products (id, name, brand, price) values (195, 'Trueblue - Blueberry Cranberry', 'Katz', 95);
insert into products (id, name, brand, price) values (196, 'Pumpkin - Seed', 'Nlounge', 44);
insert into products (id, name, brand, price) values (197, 'Pork - Smoked Back Bacon', 'Yodo', 73);
insert into products (id, name, brand, price) values (198, 'Split Peas - Green, Dry', 'Flashpoint', 64);
insert into products (id, name, brand, price) values (199, 'Coffee Cup 12oz 5342cd', 'Bubblemix', 18);
insert into products (id, name, brand, price) values (200, 'Oil - Hazelnut', 'Zoomdog', 46);
insert into products (id, name, brand, price) values (201, 'Lettuce - Lolla Rosa', 'Devshare', 20);
insert into products (id, name, brand, price) values (202, 'Garlic - Elephant', 'Aibox', 94);
insert into products (id, name, brand, price) values (203, 'Wine - Merlot Vina Carmen', 'Tanoodle', 42);
insert into products (id, name, brand, price) values (204, 'Tart Shells - Barquettes, Savory', 'Skinder', 19);
insert into products (id, name, brand, price) values (205, 'Wine - Magnotta, White', 'Jabbersphere', 75);
insert into products (id, name, brand, price) values (206, 'Bread - Triangle White', 'Geba', 35);
insert into products (id, name, brand, price) values (207, 'Cardamon Seed / Pod', 'Tagtune', 99);
insert into products (id, name, brand, price) values (208, 'Tart Shells - Sweet, 3', 'Dablist', 41);
insert into products (id, name, brand, price) values (209, 'Muffin Carrot - Individual', 'Livetube', 6);
insert into products (id, name, brand, price) values (210, 'Spice - Pepper Portions', 'Realbuzz', 64);
insert into products (id, name, brand, price) values (211, 'Wine - Fat Bastard Merlot', 'Eadel', 56);
insert into products (id, name, brand, price) values (212, 'Mints - Striped Red', 'Youbridge', 80);
insert into products (id, name, brand, price) values (213, 'Kellogs Cereal In A Cup', 'Brightdog', 42);
insert into products (id, name, brand, price) values (214, 'Butter - Pod', 'Devpoint', 37);
insert into products (id, name, brand, price) values (215, 'Pork Casing', 'Topdrive', 36);
insert into products (id, name, brand, price) values (216, 'Cup - Paper 10oz 92959', 'Thoughtstorm', 74);
insert into products (id, name, brand, price) values (217, 'Pork - Sausage Casing', 'Twitterwire', 78);
insert into products (id, name, brand, price) values (218, 'Pork - Loin, Boneless', 'Roomm', 62);
insert into products (id, name, brand, price) values (219, 'Bacardi Limon', 'Photolist', 53);
insert into products (id, name, brand, price) values (220, 'Contreau', 'Cogibox', 87);
insert into products (id, name, brand, price) values (221, 'Lettuce - Curly Endive', 'Aibox', 1);
insert into products (id, name, brand, price) values (222, 'Bar Special K', 'Plajo', 44);
insert into products (id, name, brand, price) values (223, 'Pie Box - Cello Window 2.5', 'Zoomcast', 74);
insert into products (id, name, brand, price) values (224, 'Bay Leaf Fresh', 'Teklist', 8);
insert into products (id, name, brand, price) values (225, 'Squash - Pattypan, Yellow', 'Tambee', 45);
insert into products (id, name, brand, price) values (226, 'Ecolab - Lime - A - Way 4/4 L', 'Demimbu', 46);
insert into products (id, name, brand, price) values (227, 'Truffle - Whole Black Peeled', 'Thoughtblab', 19);
insert into products (id, name, brand, price) values (228, 'Lid - High Heat, Super Clear', 'Kare', 74);
insert into products (id, name, brand, price) values (229, 'Yogurt - Plain', 'Voolith', 11);
insert into products (id, name, brand, price) values (230, 'Pie Shell - 9', 'Quamba', 56);
insert into products (id, name, brand, price) values (231, 'Sandwich Wrap', 'Quimba', 16);
insert into products (id, name, brand, price) values (232, 'Brownies - Two Bite, Chocolate', 'Jabberstorm', 7);
insert into products (id, name, brand, price) values (233, 'Pectin', 'Aivee', 81);
insert into products (id, name, brand, price) values (234, 'Lemonade - Island Tea, 591 Ml', 'Bubblebox', 80);
insert into products (id, name, brand, price) values (235, 'Icecream Bar - Del Monte', 'Yodo', 62);
insert into products (id, name, brand, price) values (236, 'Sour Cream', 'Ntags', 62);
insert into products (id, name, brand, price) values (237, 'Chicken - Livers', 'Viva', 44);
insert into products (id, name, brand, price) values (238, 'Silicone Paper 16.5x24', 'Browsedrive', 70);
insert into products (id, name, brand, price) values (239, 'Cherries - Frozen', 'Livetube', 88);
insert into products (id, name, brand, price) values (240, 'Lamb Leg - Bone - In Nz', 'Trudoo', 62);
insert into products (id, name, brand, price) values (241, 'Lemon Pepper', 'Topicshots', 63);
insert into products (id, name, brand, price) values (242, 'Sea Urchin', 'Flashspan', 92);
insert into products (id, name, brand, price) values (243, 'Muffin - Carrot Individual Wrap', 'Feednation', 1);
insert into products (id, name, brand, price) values (244, 'Crab - Dungeness, Whole', 'Kwinu', 18);
insert into products (id, name, brand, price) values (245, 'Wine - White, Cooking', 'Tazz', 23);
insert into products (id, name, brand, price) values (246, 'Food Colouring - Pink', 'Yambee', 62);
insert into products (id, name, brand, price) values (247, 'Horseradish - Prepared', 'Jabbersphere', 54);
insert into products (id, name, brand, price) values (248, 'Wine - Domaine Boyar Royal', 'Thoughtstorm', 23);
insert into products (id, name, brand, price) values (249, 'Venison - Denver Leg Boneless', 'Flipstorm', 71);
insert into products (id, name, brand, price) values (250, 'Sesame Seed Black', 'Edgeclub', 28);
insert into products (id, name, brand, price) values (251, 'Celery', 'Ailane', 81);
insert into products (id, name, brand, price) values (252, 'Bagelers', 'Wikizz', 50);
insert into products (id, name, brand, price) values (253, 'Basil - Primerba, Paste', 'Kanoodle', 64);
insert into products (id, name, brand, price) values (254, 'Mushroom - Porcini, Dry', 'Jabbersphere', 58);
insert into products (id, name, brand, price) values (255, 'Coffee - Cafe Moreno', 'Kazu', 44);
insert into products (id, name, brand, price) values (256, 'Venison - Striploin', 'Skalith', 63);
insert into products (id, name, brand, price) values (257, 'Mushroom - Morel Frozen', 'Jayo', 1);
insert into products (id, name, brand, price) values (258, 'Cookies - Amaretto', 'Yakidoo', 57);
insert into products (id, name, brand, price) values (259, 'Wine - Sawmill Creek Autumn', 'Miboo', 93);
insert into products (id, name, brand, price) values (260, 'Rice Pilaf, Dry,package', 'Dabshots', 100);
insert into products (id, name, brand, price) values (261, 'Dc - Sakura Fu', 'Skiba', 38);
insert into products (id, name, brand, price) values (262, 'Lamb Rack - Ontario', 'Reallinks', 23);
insert into products (id, name, brand, price) values (263, 'Spinach - Packaged', 'Quire', 70);
insert into products (id, name, brand, price) values (264, 'Milk - Skim', 'Yakidoo', 75);
insert into products (id, name, brand, price) values (265, 'Kiwi', 'Chatterbridge', 12);
insert into products (id, name, brand, price) values (266, 'Glass - Wine, Plastic, Clear 5 Oz', 'Leenti', 37);
insert into products (id, name, brand, price) values (267, 'Wine - Conde De Valdemar', 'Livepath', 91);
insert into products (id, name, brand, price) values (268, 'Wine - Puligny Montrachet A.', 'Devbug', 73);
insert into products (id, name, brand, price) values (269, 'Versatainer Nc - 8288', 'Quaxo', 72);
insert into products (id, name, brand, price) values (270, 'Pear - Asian', 'Eamia', 72);
insert into products (id, name, brand, price) values (271, 'Sauce - Apple, Unsweetened', 'Janyx', 40);
insert into products (id, name, brand, price) values (272, 'Kale - Red', 'Voonte', 7);
insert into products (id, name, brand, price) values (273, 'Ecolab - Hobart Washarm End Cap', 'Ainyx', 93);
insert into products (id, name, brand, price) values (274, 'Uniform Linen Charge', 'Rhyzio', 16);
insert into products (id, name, brand, price) values (275, 'Cherries - Bing, Canned', 'Einti', 21);
insert into products (id, name, brand, price) values (276, 'Honey - Comb', 'Meejo', 57);
insert into products (id, name, brand, price) values (277, 'Pate - Liver', 'Ailane', 57);
insert into products (id, name, brand, price) values (278, 'Cauliflower', 'Bubblemix', 92);
insert into products (id, name, brand, price) values (279, 'Wine - Rubyport', 'Kwinu', 64);
insert into products (id, name, brand, price) values (280, 'Chocolate - Feathers', 'Jazzy', 76);
insert into products (id, name, brand, price) values (281, 'Peppercorns - Pink', 'Brightbean', 39);
insert into products (id, name, brand, price) values (282, 'Oregano - Dry, Rubbed', 'Plambee', 16);
insert into products (id, name, brand, price) values (283, 'Chicken - Soup Base', 'InnoZ', 19);
insert into products (id, name, brand, price) values (284, 'Pants Custom Dry Clean', 'Jabberstorm', 99);
insert into products (id, name, brand, price) values (285, 'Extract - Rum', 'Brainlounge', 16);
insert into products (id, name, brand, price) values (286, 'Island Oasis - Pina Colada', 'Aimbo', 81);
insert into products (id, name, brand, price) values (287, 'Rice - Basmati', 'Thoughtmix', 90);
insert into products (id, name, brand, price) values (288, 'Cheese - Pied De Vents', 'Realfire', 90);
insert into products (id, name, brand, price) values (289, 'Turkey - Breast, Bone - In', 'Babblestorm', 70);
insert into products (id, name, brand, price) values (290, 'Pasta - Canelloni, Single Serve', 'Mymm', 63);
insert into products (id, name, brand, price) values (291, 'Dr. Pepper - 355ml', 'Tekfly', 1);
insert into products (id, name, brand, price) values (292, 'Chicken - Thigh, Bone In', 'Thoughtworks', 48);
insert into products (id, name, brand, price) values (293, 'Bread - Crumbs, Bulk', 'Twitternation', 97);
insert into products (id, name, brand, price) values (294, 'Napkin - Beverage 1 Ply', 'Yodoo', 15);
insert into products (id, name, brand, price) values (295, 'Seedlings - Mix, Organic', 'Flipbug', 21);
insert into products (id, name, brand, price) values (296, 'Cake - Pancake', 'Realfire', 75);
insert into products (id, name, brand, price) values (297, 'Carbonated Water - Peach', 'Dabvine', 66);
insert into products (id, name, brand, price) values (298, 'Wine - Beaujolais Villages', 'Oyoba', 57);
insert into products (id, name, brand, price) values (299, 'Potato - Sweet', 'Realpoint', 61);
insert into products (id, name, brand, price) values (300, 'Kahlua', 'Quaxo', 37);
insert into products (id, name, brand, price) values (301, 'Tarts Assorted', 'Brightbean', 40);
insert into products (id, name, brand, price) values (302, 'Pasta - Bauletti, Chicken White', 'Fatz', 65);
insert into products (id, name, brand, price) values (303, 'Lamb - Whole, Fresh', 'Eimbee', 61);
insert into products (id, name, brand, price) values (304, 'Wine - Hardys Bankside Shiraz', 'Thoughtstorm', 75);
insert into products (id, name, brand, price) values (305, 'Wine - White, Ej', 'Photobug', 3);
insert into products (id, name, brand, price) values (306, 'Rice - Aborio', 'Einti', 3);
insert into products (id, name, brand, price) values (307, 'Beer - True North Strong Ale', 'Vitz', 45);
insert into products (id, name, brand, price) values (308, 'Croissant, Raw - Mini', 'Demivee', 51);
insert into products (id, name, brand, price) values (309, 'Pepsi, 355 Ml', 'Skinder', 56);
insert into products (id, name, brand, price) values (310, 'Turkey - Whole, Fresh', 'Meejo', 74);
insert into products (id, name, brand, price) values (311, 'Dooleys Toffee', 'Yodel', 26);
insert into products (id, name, brand, price) values (312, 'Soup - Boston Clam Chowder', 'Camido', 34);
insert into products (id, name, brand, price) values (313, 'Beer - Maudite', 'Realbridge', 39);
insert into products (id, name, brand, price) values (314, 'Pasta - Lasagna Noodle, Frozen', 'Tanoodle', 1);
insert into products (id, name, brand, price) values (315, 'Salmon - Whole, 4 - 6 Pounds', 'Browsecat', 17);
insert into products (id, name, brand, price) values (316, 'Pasta - Fettuccine, Egg, Fresh', 'Meejo', 86);
insert into products (id, name, brand, price) values (317, 'Butter - Pod', 'Riffpath', 29);
insert into products (id, name, brand, price) values (318, 'Daves Island Stinger', 'Photobug', 66);
insert into products (id, name, brand, price) values (319, 'Tomatillo', 'Vipe', 33);
insert into products (id, name, brand, price) values (320, 'Soup - Campbells, Lentil', 'Eimbee', 75);
insert into products (id, name, brand, price) values (321, 'Dc - Sakura Fu', 'Kwinu', 15);
insert into products (id, name, brand, price) values (322, 'Butter - Salted', 'Vitz', 71);
insert into products (id, name, brand, price) values (323, 'Sherbet - Raspberry', 'Jetwire', 81);
insert into products (id, name, brand, price) values (324, 'Banana - Leaves', 'Twitterlist', 14);
insert into products (id, name, brand, price) values (325, 'Wine - Vovray Sec Domaine Huet', 'Rhynyx', 90);
insert into products (id, name, brand, price) values (326, 'Tray - Foam, Square 4 - S', 'Quinu', 86);
insert into products (id, name, brand, price) values (327, 'Turkey - Breast, Smoked', 'Gabcube', 82);
insert into products (id, name, brand, price) values (328, 'Ice Cream Bar - Oreo Cone', 'Eidel', 40);
insert into products (id, name, brand, price) values (329, 'Plums - Red', 'Skivee', 99);
insert into products (id, name, brand, price) values (330, 'Venison - Ground', 'Myworks', 67);
insert into products (id, name, brand, price) values (331, 'Honey - Lavender', 'Voonte', 96);
insert into products (id, name, brand, price) values (332, 'Chicken - Livers', 'Blogtag', 11);
insert into products (id, name, brand, price) values (333, 'Curry Powder', 'Thoughtblab', 21);
insert into products (id, name, brand, price) values (334, 'Lettuce - Romaine, Heart', 'Zoombeat', 92);
insert into products (id, name, brand, price) values (335, 'Glaze - Apricot', 'Teklist', 78);
insert into products (id, name, brand, price) values (336, 'Wine - Penfolds Koonuga Hill', 'Yombu', 47);
insert into products (id, name, brand, price) values (337, 'Soup Bowl Clear 8oz92008', 'Bluezoom', 66);
insert into products (id, name, brand, price) values (338, 'Muffin Carrot - Individual', 'Edgepulse', 6);
insert into products (id, name, brand, price) values (339, 'Soup - Campbells Beef Strogonoff', 'Thoughtmix', 94);
insert into products (id, name, brand, price) values (340, 'Beer - True North Strong Ale', 'Cogilith', 77);
insert into products (id, name, brand, price) values (341, 'Pepper - Paprika, Hungarian', 'Demizz', 59);
insert into products (id, name, brand, price) values (342, 'Cleaner - Lime Away', 'Riffwire', 99);
insert into products (id, name, brand, price) values (343, 'Pork - Belly Fresh', 'Fivespan', 100);
insert into products (id, name, brand, price) values (344, 'Tea - Vanilla Chai', 'Voomm', 84);
insert into products (id, name, brand, price) values (345, 'Bandage - Flexible Neon', 'Twitterworks', 39);
insert into products (id, name, brand, price) values (346, 'Glass Clear 7 Oz Xl', 'Skyndu', 25);
insert into products (id, name, brand, price) values (347, 'Beef - Ox Tongue, Pickled', 'Tagopia', 77);
insert into products (id, name, brand, price) values (348, 'Appetizer - Shrimp Puff', 'Blognation', 2);
insert into products (id, name, brand, price) values (349, 'Kaffir Lime Leaves', 'Snaptags', 76);
insert into products (id, name, brand, price) values (350, 'Cleaner - Bleach', 'Jabbersphere', 83);
insert into products (id, name, brand, price) values (351, 'Sauce - Roasted Red Pepper', 'Flipopia', 34);
insert into products (id, name, brand, price) values (352, 'Relish', 'Gigabox', 67);
insert into products (id, name, brand, price) values (353, 'Sauce - Alfredo', 'Dabtype', 49);
insert into products (id, name, brand, price) values (354, 'Juice - Grapefruit, 341 Ml', 'Voonyx', 40);
insert into products (id, name, brand, price) values (355, 'Sugar - White Packet', 'Npath', 95);
insert into products (id, name, brand, price) values (356, 'Beef - Rib Eye Aaa', 'Buzzster', 13);
insert into products (id, name, brand, price) values (357, 'Sauce - Balsamic Viniagrette', 'Devpulse', 42);
insert into products (id, name, brand, price) values (358, 'Wine - White, Riesling, Henry Of', 'Divanoodle', 60);
insert into products (id, name, brand, price) values (359, 'Corn Kernels - Frozen', 'Aimbo', 23);
insert into products (id, name, brand, price) values (360, 'Beer - Muskoka Cream Ale', 'Divavu', 37);
insert into products (id, name, brand, price) values (361, 'Lentils - Green Le Puy', 'Flipbug', 78);
insert into products (id, name, brand, price) values (362, 'Cauliflower', 'Skyble', 31);
insert into products (id, name, brand, price) values (363, 'Nut - Walnut, Chopped', 'Kazu', 19);
insert into products (id, name, brand, price) values (364, 'Salmon Atl.whole 8 - 10 Lb', 'Oyondu', 64);
insert into products (id, name, brand, price) values (365, 'Sauce - Balsamic Viniagrette', 'Abata', 22);
insert into products (id, name, brand, price) values (366, 'Container - Hngd Cll Blk 7x7x3', 'Kwilith', 100);
insert into products (id, name, brand, price) values (367, 'Rum - White, Gg White', 'Gabcube', 20);
insert into products (id, name, brand, price) values (368, 'Soup - Campbells, Cream Of', 'Skimia', 96);
insert into products (id, name, brand, price) values (369, 'Liquid Aminios Acid - Braggs', 'Mynte', 61);
insert into products (id, name, brand, price) values (370, 'The Pop Shoppe - Lime Rickey', 'Wordpedia', 95);
insert into products (id, name, brand, price) values (371, 'Lamb - Bones', 'Kanoodle', 2);
insert into products (id, name, brand, price) values (372, 'Crab - Blue, Frozen', 'Nlounge', 63);
insert into products (id, name, brand, price) values (373, 'Russian Prince', 'Skidoo', 65);
insert into products (id, name, brand, price) values (374, 'Hinge W Undercut', 'Jabbercube', 79);
insert into products (id, name, brand, price) values (375, 'Cod - Fillets', 'Realbridge', 13);
insert into products (id, name, brand, price) values (376, 'Carroway Seed', 'Skyble', 67);
insert into products (id, name, brand, price) values (377, 'Trueblue - Blueberry Cranberry', 'Edgewire', 73);
insert into products (id, name, brand, price) values (378, 'Squash - Guords', 'Riffwire', 84);
insert into products (id, name, brand, price) values (379, 'Coriander - Ground', 'Dabjam', 15);
insert into products (id, name, brand, price) values (380, 'Wine - Gato Negro Cabernet', 'Quaxo', 66);
insert into products (id, name, brand, price) values (381, 'Beef - Top Butt Aaa', 'Photobug', 54);
insert into products (id, name, brand, price) values (382, 'Shrimp - Black Tiger 26/30', 'Jaxnation', 31);
insert into products (id, name, brand, price) values (383, 'Five Alive Citrus', 'Divanoodle', 24);
insert into products (id, name, brand, price) values (384, 'Papayas', 'Demivee', 39);
insert into products (id, name, brand, price) values (385, 'External Supplier', 'Zazio', 11);
insert into products (id, name, brand, price) values (386, 'Pork Salted Bellies', 'Gabtune', 46);
insert into products (id, name, brand, price) values (387, 'Wine - Ice Wine', 'Dablist', 71);
insert into products (id, name, brand, price) values (388, 'Pasta - Fett Alfredo, Single Serve', 'Yotz', 61);
insert into products (id, name, brand, price) values (389, 'Bread - Granary Small Pull', 'Oba', 86);
insert into products (id, name, brand, price) values (390, 'Beans - Turtle, Black, Dry', 'Fiveclub', 3);
insert into products (id, name, brand, price) values (391, 'Lotus Leaves', 'Voonyx', 64);
insert into products (id, name, brand, price) values (392, 'Filter - Coffee', 'Wikizz', 49);
insert into products (id, name, brand, price) values (393, 'Truffle Cups - Red', 'Vipe', 37);
insert into products (id, name, brand, price) values (394, 'Appetizer - Shrimp Puff', 'Roodel', 88);
insert into products (id, name, brand, price) values (395, 'Wine - Chianti Classico Riserva', 'Plambee', 80);
insert into products (id, name, brand, price) values (396, 'Sage Ground Wiberg', 'Jetwire', 96);
insert into products (id, name, brand, price) values (397, 'Sauce - Thousand Island', 'Babblestorm', 13);
insert into products (id, name, brand, price) values (398, 'Napkin - Beverge, White 2 - Ply', 'Mydo', 35);
insert into products (id, name, brand, price) values (399, 'Soup - Campbells Bean Medley', 'Livetube', 7);
insert into products (id, name, brand, price) values (400, 'Southern Comfort', 'Eamia', 32);
insert into products (id, name, brand, price) values (401, 'Cheese Cloth No 100', 'Ooba', 94);
insert into products (id, name, brand, price) values (402, 'V8 Splash Strawberry Kiwi', 'Twitterlist', 76);
insert into products (id, name, brand, price) values (403, 'Zucchini - Yellow', 'Brainlounge', 72);
insert into products (id, name, brand, price) values (404, 'Creamers - 10%', 'Riffpedia', 97);
insert into products (id, name, brand, price) values (405, 'Parasol Pick Stir Stick', 'Meembee', 87);
insert into products (id, name, brand, price) values (406, 'Cup - 3.5oz, Foam', 'Eamia', 71);
insert into products (id, name, brand, price) values (407, 'Squash - Guords', 'Jabbersphere', 15);
insert into products (id, name, brand, price) values (408, 'Turkey - Breast, Bone - In', 'Browsecat', 46);
insert into products (id, name, brand, price) values (409, 'Ecolab - Ster Bac', 'Kaymbo', 65);
insert into products (id, name, brand, price) values (410, 'Scallops 60/80 Iqf', 'Skaboo', 2);
insert into products (id, name, brand, price) values (411, 'Pastry - Cherry Danish - Mini', 'Fivebridge', 98);
insert into products (id, name, brand, price) values (412, 'Wine - White, Ej', 'Topicblab', 27);
insert into products (id, name, brand, price) values (413, 'Apple - Royal Gala', 'Gevee', 62);
insert into products (id, name, brand, price) values (414, 'Sauce - Salsa', 'Voomm', 94);
insert into products (id, name, brand, price) values (415, 'Lamb - Shanks', 'Thoughtstorm', 64);
insert into products (id, name, brand, price) values (416, 'Kale - Red', 'Linklinks', 91);
insert into products (id, name, brand, price) values (417, 'Soup - Knorr, Country Bean', 'Gabspot', 95);
insert into products (id, name, brand, price) values (418, 'Couscous', 'Avamba', 14);
insert into products (id, name, brand, price) values (419, 'Soup - Cream Of Broccoli, Dry', 'Agimba', 59);
insert into products (id, name, brand, price) values (420, 'Water - Evian 355 Ml', 'Skinte', 6);
insert into products (id, name, brand, price) values (421, 'Beef - Top Sirloin', 'Abata', 46);
insert into products (id, name, brand, price) values (422, 'Sobe - Liz Blizz', 'Livetube', 9);
insert into products (id, name, brand, price) values (423, 'Sauce - Balsamic Viniagrette', 'Livefish', 6);
insert into products (id, name, brand, price) values (424, 'Lobster - Tail 6 Oz', 'Viva', 28);
insert into products (id, name, brand, price) values (425, 'Huck Towels White', 'Quatz', 86);
insert into products (id, name, brand, price) values (426, 'Soup - Campbells Mushroom', 'Voonder', 12);
insert into products (id, name, brand, price) values (427, 'Coffee - Irish Cream', 'Innotype', 61);
insert into products (id, name, brand, price) values (428, 'Rum - Coconut, Malibu', 'Plambee', 30);
insert into products (id, name, brand, price) values (429, 'Pork - Suckling Pig', 'Eimbee', 80);
insert into products (id, name, brand, price) values (430, 'Appetiser - Bought', 'Agivu', 17);
insert into products (id, name, brand, price) values (431, 'Ostrich - Fan Fillet', 'Chatterpoint', 10);
insert into products (id, name, brand, price) values (432, 'Ice Cream Bar - Drumstick', 'Quimba', 40);
insert into products (id, name, brand, price) values (433, 'Quail - Whole, Bone - In', 'Trudeo', 100);
insert into products (id, name, brand, price) values (434, 'Vodka - Moskovskaya', 'Kazio', 36);
insert into products (id, name, brand, price) values (435, 'Cream Of Tartar', 'Thoughtstorm', 18);
insert into products (id, name, brand, price) values (436, 'Lamb - Pieces, Diced', 'Brainsphere', 13);
insert into products (id, name, brand, price) values (437, 'Veal - Leg', 'Jaloo', 40);
insert into products (id, name, brand, price) values (438, 'Wine - Spumante Bambino White', 'Thoughtblab', 81);
insert into products (id, name, brand, price) values (439, 'Anchovy In Oil', 'Voomm', 9);
insert into products (id, name, brand, price) values (440, 'Chocolate - Dark Callets', 'Eabox', 49);
insert into products (id, name, brand, price) values (441, 'Wine - Zinfandel California 2002', 'Camimbo', 58);
insert into products (id, name, brand, price) values (442, 'Cookie Trail Mix', 'Oyonder', 55);
insert into products (id, name, brand, price) values (443, 'Sandwich Wrap', 'Jetpulse', 50);
insert into products (id, name, brand, price) values (444, 'Syrup - Pancake', 'Twitterwire', 3);
insert into products (id, name, brand, price) values (445, 'Wine - Redchard Merritt', 'Kwideo', 52);
insert into products (id, name, brand, price) values (446, 'Barley - Pearl', 'Yodel', 24);
insert into products (id, name, brand, price) values (447, 'Chickensplit Half', 'Jaxspan', 63);
insert into products (id, name, brand, price) values (448, 'Wine - White, Pelee Island', 'Jabbercube', 8);
insert into products (id, name, brand, price) values (449, 'Beer - Muskoka Cream Ale', 'Kwilith', 51);
insert into products (id, name, brand, price) values (450, 'Peach - Halves', 'Dabjam', 56);
insert into products (id, name, brand, price) values (451, 'Sambuca Cream', 'Podcat', 28);
insert into products (id, name, brand, price) values (452, 'Soup Campbells Mexicali Tortilla', 'Shufflester', 36);
insert into products (id, name, brand, price) values (453, 'Chinese Foods - Chicken Wing', 'Ozu', 44);
insert into products (id, name, brand, price) values (454, 'Chicken - White Meat, No Tender', 'Yakidoo', 80);
insert into products (id, name, brand, price) values (455, 'Table Cloth 54x54 Colour', 'Voonix', 19);
insert into products (id, name, brand, price) values (456, 'Rolled Oats', 'Dabtype', 37);
insert into products (id, name, brand, price) values (457, 'Flour - All Purpose', 'Yoveo', 40);
insert into products (id, name, brand, price) values (458, 'Hold Up Tool Storage Rack', 'Chatterpoint', 86);
insert into products (id, name, brand, price) values (459, 'Wine - Chateau Bonnet', 'Kwideo', 67);
insert into products (id, name, brand, price) values (460, 'Juice - Apple Cider', 'Babbleset', 83);
insert into products (id, name, brand, price) values (461, 'French Pastry - Mini Chocolate', 'Skipstorm', 75);
insert into products (id, name, brand, price) values (462, 'Whmis Spray Bottle Graduated', 'Eadel', 59);
insert into products (id, name, brand, price) values (463, 'Muffin - Bran Ind Wrpd', 'Feedspan', 44);
insert into products (id, name, brand, price) values (464, 'Jello - Assorted', 'Zoombox', 81);
insert into products (id, name, brand, price) values (465, 'Godiva White Chocolate', 'Tagchat', 27);
insert into products (id, name, brand, price) values (466, 'Mushrooms - Honey', 'Topicware', 26);
insert into products (id, name, brand, price) values (467, 'Sterno - Chafing Dish Fuel', 'Quinu', 91);
insert into products (id, name, brand, price) values (468, 'Tofu - Firm', 'Twimm', 59);
insert into products (id, name, brand, price) values (469, 'Guinea Fowl', 'Wikizz', 82);
insert into products (id, name, brand, price) values (470, 'Parasol Pick Stir Stick', 'Realmix', 82);
insert into products (id, name, brand, price) values (471, 'Muffin - Banana Nut Individual', 'Divavu', 55);
insert into products (id, name, brand, price) values (472, 'Soup - Campbells Mushroom', 'Skynoodle', 38);
insert into products (id, name, brand, price) values (473, 'Bowl 12 Oz - Showcase 92012', 'Kazu', 64);
insert into products (id, name, brand, price) values (474, 'Bread - Petit Baguette', 'Tagchat', 99);
insert into products (id, name, brand, price) values (475, 'Chips - Assorted', 'Devbug', 7);
insert into products (id, name, brand, price) values (476, 'Appetizer - Tarragon Chicken', 'Oodoo', 89);
insert into products (id, name, brand, price) values (477, 'Beef - Sushi Flat Iron Steak', 'Roomm', 74);
insert into products (id, name, brand, price) values (478, 'Sausage - Blood Pudding', 'Flashpoint', 5);
insert into products (id, name, brand, price) values (479, 'Honey - Liquid', 'Oba', 25);
insert into products (id, name, brand, price) values (480, 'Table Cloth 54x54 White', 'Vinder', 24);
insert into products (id, name, brand, price) values (481, 'Lamb - Bones', 'Quimm', 81);
insert into products (id, name, brand, price) values (482, 'Parsley Italian - Fresh', 'LiveZ', 46);
insert into products (id, name, brand, price) values (483, 'Island Oasis - Pina Colada', 'Skinte', 38);
insert into products (id, name, brand, price) values (484, 'Capers - Pickled', 'Twinder', 40);
insert into products (id, name, brand, price) values (485, 'Bread - Onion Focaccia', 'Youspan', 40);
insert into products (id, name, brand, price) values (486, 'Cinnamon Rolls', 'Skivee', 5);
insert into products (id, name, brand, price) values (487, 'Tuna - Salad Premix', 'Babbleopia', 37);
insert into products (id, name, brand, price) values (488, 'Wine - Ruffino Chianti', 'Kwilith', 50);
insert into products (id, name, brand, price) values (489, 'Chicken - Leg / Back Attach', 'Wordpedia', 61);
insert into products (id, name, brand, price) values (490, 'Spring Roll Veg Mini', 'Mita', 68);
insert into products (id, name, brand, price) values (491, 'Cup - Paper 10oz 92959', 'Jabberstorm', 96);
insert into products (id, name, brand, price) values (492, 'Beef - Flank Steak', 'Dynava', 4);
insert into products (id, name, brand, price) values (493, 'Bread - Hamburger Buns', 'Innotype', 35);
insert into products (id, name, brand, price) values (494, 'Wine - White, Chardonnay', 'Babbleset', 2);
insert into products (id, name, brand, price) values (495, 'Food Colouring - Green', 'Youfeed', 41);
insert into products (id, name, brand, price) values (496, 'Tarragon - Fresh', 'Meembee', 67);
insert into products (id, name, brand, price) values (497, 'Bread - Bagels, Plain', 'Thoughtmix', 21);
insert into products (id, name, brand, price) values (498, 'Calvados - Boulard', 'Zoozzy', 39);
insert into products (id, name, brand, price) values (499, 'Vermouth - White, Cinzano', 'Wikizz', 88);
insert into products (id, name, brand, price) values (500, 'Nantucket - 518ml', 'Eazzy', 60);
insert into products (id, name, brand, price) values (501, 'Kellogs Cereal In A Cup', 'Realbuzz', 99);
insert into products (id, name, brand, price) values (502, 'Tomatoes - Hot House', 'Flashdog', 61);
insert into products (id, name, brand, price) values (503, 'Foil Wrap', 'Tekfly', 33);
insert into products (id, name, brand, price) values (504, 'Veal - Inside Round / Top, Lean', 'Meevee', 6);
insert into products (id, name, brand, price) values (505, 'Lemonade - Island Tea, 591 Ml', 'Ozu', 61);
insert into products (id, name, brand, price) values (506, 'Muffins - Assorted', 'Twitterbridge', 74);
insert into products (id, name, brand, price) values (507, 'Cake - Cake Sheet Macaroon', 'Youopia', 47);
insert into products (id, name, brand, price) values (508, 'Sauerkraut', 'Kayveo', 8);
insert into products (id, name, brand, price) values (509, 'Isomalt', 'Babbleopia', 97);
insert into products (id, name, brand, price) values (510, 'Wine - Pinot Noir Latour', 'Zoomlounge', 29);
insert into products (id, name, brand, price) values (511, 'Mushroom - Enoki, Dry', 'Oloo', 51);
insert into products (id, name, brand, price) values (512, 'Cookie Double Choco', 'Voomm', 17);
insert into products (id, name, brand, price) values (513, 'Flour - Bran, Red', 'Jatri', 15);
insert into products (id, name, brand, price) values (514, 'Onions - White', 'Brightbean', 59);
insert into products (id, name, brand, price) values (515, 'Beef - Tenderloin Tails', 'Skimia', 80);
insert into products (id, name, brand, price) values (516, 'Wine - Montecillo Rioja Crianza', 'Innotype', 17);
insert into products (id, name, brand, price) values (517, 'Soup Campbells Beef With Veg', 'Shuffletag', 40);
insert into products (id, name, brand, price) values (518, 'Appetizer - Lobster Phyllo Roll', 'Meezzy', 39);
insert into products (id, name, brand, price) values (519, 'Muffin Mix - Chocolate Chip', 'Linkbridge', 84);
insert into products (id, name, brand, price) values (520, 'Wine - Fontanafredda Barolo', 'Twinte', 42);
insert into products (id, name, brand, price) values (521, 'Pasta - Linguini, Dry', 'Mudo', 55);
insert into products (id, name, brand, price) values (522, 'Piping - Bags Quizna', 'Divanoodle', 89);
insert into products (id, name, brand, price) values (523, 'Bread - Rolls, Corn', 'Yodo', 88);
insert into products (id, name, brand, price) values (524, 'Pork Loin Cutlets', 'Jazzy', 74);
insert into products (id, name, brand, price) values (525, 'Pork - Smoked Kassler', 'Katz', 79);
insert into products (id, name, brand, price) values (526, 'Muffin Orange Individual', 'Avaveo', 3);
insert into products (id, name, brand, price) values (527, 'Honey - Comb', 'Zoomlounge', 69);
insert into products (id, name, brand, price) values (528, 'Oil - Olive Bertolli', 'Livefish', 89);
insert into products (id, name, brand, price) values (529, 'Dip - Tapenade', 'Oyoba', 67);
insert into products (id, name, brand, price) values (530, 'Wine - Niagara Peninsula Vqa', 'Tanoodle', 41);
insert into products (id, name, brand, price) values (531, 'Flour - Rye', 'Yotz', 66);
insert into products (id, name, brand, price) values (532, 'Vinegar - Champagne', 'Gigaclub', 85);
insert into products (id, name, brand, price) values (533, 'Longos - Grilled Veg Sandwiches', 'Wordtune', 41);
insert into products (id, name, brand, price) values (534, 'Red Currants', 'Innotype', 96);
insert into products (id, name, brand, price) values (535, 'Kaffir Lime Leaves', 'Livetube', 12);
insert into products (id, name, brand, price) values (536, 'Wine - Magnotta, White', 'Flipbug', 74);
insert into products (id, name, brand, price) values (537, 'Tabasco Sauce, 2 Oz', 'Meemm', 34);
insert into products (id, name, brand, price) values (538, 'Bar - Sweet And Salty Chocolate', 'Zoombeat', 47);
insert into products (id, name, brand, price) values (539, 'Wine - Cousino Macul Antiguas', 'Buzzdog', 82);
insert into products (id, name, brand, price) values (540, 'Wine - Touraine Azay - Le - Rideau', 'Myworks', 43);
insert into products (id, name, brand, price) values (541, 'Straw - Regular', 'Buzzbean', 45);
insert into products (id, name, brand, price) values (542, 'Syrup - Monin - Granny Smith', 'Meedoo', 14);
insert into products (id, name, brand, price) values (543, 'Marjoram - Dried, Rubbed', 'Topdrive', 58);
insert into products (id, name, brand, price) values (544, 'Sprite - 355 Ml', 'Twitterbridge', 6);
insert into products (id, name, brand, price) values (545, 'Chicken - Diced, Cooked', 'Brightdog', 27);
insert into products (id, name, brand, price) values (546, 'Table Cloth 81x81 White', 'Oyondu', 40);
insert into products (id, name, brand, price) values (547, 'Pork - Ham Hocks - Smoked', 'Brainsphere', 87);
insert into products (id, name, brand, price) values (548, 'Tarragon - Primerba, Paste', 'Topdrive', 80);
insert into products (id, name, brand, price) values (549, 'Table Cloth 81x81 Colour', 'Skinix', 8);
insert into products (id, name, brand, price) values (550, 'Ice Cream Bar - Hageen Daz To', 'Topicstorm', 9);
insert into products (id, name, brand, price) values (551, 'Soup Campbells Beef With Veg', 'Voolia', 82);
insert into products (id, name, brand, price) values (552, 'Beef - Tender Tips', 'Babbleopia', 2);
insert into products (id, name, brand, price) values (553, 'Mcgillicuddy Vanilla Schnap', 'Mydo', 54);
insert into products (id, name, brand, price) values (554, 'Bar - Sweet And Salty Chocolate', 'Kwinu', 34);
insert into products (id, name, brand, price) values (555, 'Pastry - Chocolate Marble Tea', 'Skipstorm', 8);
insert into products (id, name, brand, price) values (556, 'Sauerkraut', 'Agivu', 75);
insert into products (id, name, brand, price) values (557, 'Lid Tray - 12in Dome', 'Meetz', 34);
insert into products (id, name, brand, price) values (558, 'Dawn Professionl Pot And Pan', 'Twitterworks', 68);
insert into products (id, name, brand, price) values (559, 'Water - Spring Water, 355 Ml', 'Livepath', 76);
insert into products (id, name, brand, price) values (560, 'Orange - Blood', 'Dazzlesphere', 41);
insert into products (id, name, brand, price) values (561, 'Rootbeer', 'Kanoodle', 44);
insert into products (id, name, brand, price) values (562, 'Chutney Sauce - Mango', 'Twinder', 43);
insert into products (id, name, brand, price) values (563, 'Yogurt - Strawberry, 175 Gr', 'Aivee', 83);
insert into products (id, name, brand, price) values (564, 'Quinoa', 'Twinte', 99);
insert into products (id, name, brand, price) values (565, 'Rum - Light, Captain Morgan', 'Edgeify', 92);
insert into products (id, name, brand, price) values (566, 'Vaccum Bag - 14x20', 'Photobean', 31);
insert into products (id, name, brand, price) values (567, 'Soup - Campbells - Tomato', 'Cogilith', 23);
insert into products (id, name, brand, price) values (568, 'Irish Cream - Butterscotch', 'Skinder', 17);
insert into products (id, name, brand, price) values (569, 'Wine - Sicilia Igt Nero Avola', 'Yodoo', 55);
insert into products (id, name, brand, price) values (570, 'Beans - Turtle, Black, Dry', 'Skipstorm', 28);
insert into products (id, name, brand, price) values (571, 'Kahlua', 'Topicstorm', 63);
insert into products (id, name, brand, price) values (572, 'Wine - Lamancha Do Crianza', 'Zooveo', 50);
insert into products (id, name, brand, price) values (573, 'Longos - Chicken Cordon Bleu', 'Leexo', 18);
insert into products (id, name, brand, price) values (574, 'Jam - Apricot', 'Voonder', 74);
insert into products (id, name, brand, price) values (575, 'Pasta - Gnocchi, Potato', 'Skyndu', 11);
insert into products (id, name, brand, price) values (576, 'Beans - Long, Chinese', 'Shuffletag', 42);
insert into products (id, name, brand, price) values (577, 'Bread - Roll, Calabrese', 'Voonder', 5);
insert into products (id, name, brand, price) values (578, 'Trout - Rainbow, Frozen', 'Ainyx', 80);
insert into products (id, name, brand, price) values (579, 'Salmon - Fillets', 'Omba', 7);
insert into products (id, name, brand, price) values (580, 'Apricots - Dried', 'Voonte', 17);
insert into products (id, name, brand, price) values (581, 'Bag Clear 10 Lb', 'Yotz', 35);
insert into products (id, name, brand, price) values (582, 'Orange Roughy 6/8 Oz', 'Skipfire', 48);
insert into products (id, name, brand, price) values (583, 'Beef - Shank', 'Oyope', 8);
insert into products (id, name, brand, price) values (584, 'Ecolab Digiclean Mild Fm', 'Mymm', 29);
insert into products (id, name, brand, price) values (585, 'Soup - Campbells, Lentil', 'Brainverse', 12);
insert into products (id, name, brand, price) values (586, 'Wine - Casillero Deldiablo', 'Mybuzz', 84);
insert into products (id, name, brand, price) values (587, 'Pike - Frozen Fillet', 'Divavu', 37);
insert into products (id, name, brand, price) values (588, 'Beer - Tetleys', 'Mynte', 74);
insert into products (id, name, brand, price) values (589, 'Sauce - Soya, Dark', 'Feedmix', 22);
insert into products (id, name, brand, price) values (590, 'Salmon - Fillets', 'Skaboo', 57);
insert into products (id, name, brand, price) values (591, 'Mackerel Whole Fresh', 'Fliptune', 41);
insert into products (id, name, brand, price) values (592, 'Napkin - Beverage 1 Ply', 'Gigabox', 62);
insert into products (id, name, brand, price) values (593, 'Rum - Light, Captain Morgan', 'Cogidoo', 14);
insert into products (id, name, brand, price) values (594, 'Bread - Dark Rye, Loaf', 'Wordtune', 74);
insert into products (id, name, brand, price) values (595, 'Flower - Leather Leaf Fern', 'Cogidoo', 35);
insert into products (id, name, brand, price) values (596, 'Pate Pans Yellow', 'Agimba', 20);
insert into products (id, name, brand, price) values (597, 'Wine - Vineland Estate Semi - Dry', 'Meevee', 55);
insert into products (id, name, brand, price) values (598, 'Oil - Avocado', 'Wordify', 15);
insert into products (id, name, brand, price) values (599, 'Dc - Frozen Momji', 'Feedmix', 44);
insert into products (id, name, brand, price) values (600, 'Vermouth - White, Cinzano', 'Demimbu', 9);
insert into products (id, name, brand, price) values (601, 'Liqueur Banana, Ramazzotti', 'JumpXS', 17);
insert into products (id, name, brand, price) values (602, 'Chicken - White Meat, No Tender', 'Fivechat', 84);
insert into products (id, name, brand, price) values (603, 'Oil - Margarine', 'Fanoodle', 81);
insert into products (id, name, brand, price) values (604, 'Bonito Flakes - Toku Katsuo', 'Skimia', 45);
insert into products (id, name, brand, price) values (605, 'Veal - Leg', 'Feedfish', 42);
insert into products (id, name, brand, price) values (606, 'Arizona - Plum Green Tea', 'Devcast', 22);
insert into products (id, name, brand, price) values (607, 'Salmon - Atlantic, Fresh, Whole', 'Blogspan', 64);
insert into products (id, name, brand, price) values (608, 'Sea Urchin', 'Jaxbean', 27);
insert into products (id, name, brand, price) values (609, 'Bread - Pita', 'Jetwire', 72);
insert into products (id, name, brand, price) values (610, 'Cup - Paper 10oz 92959', 'Riffwire', 61);
insert into products (id, name, brand, price) values (611, 'Steam Pan Full Lid', 'Bluejam', 92);
insert into products (id, name, brand, price) values (612, 'Wine - Fino Tio Pepe Gonzalez', 'Cogilith', 12);
insert into products (id, name, brand, price) values (613, 'Bread - Roll, Italian', 'Dynabox', 95);
insert into products (id, name, brand, price) values (614, 'Melon - Cantaloupe', 'Ailane', 11);
insert into products (id, name, brand, price) values (615, 'Gingerale - Diet - Schweppes', 'Feednation', 12);
insert into products (id, name, brand, price) values (616, 'Calypso - Pineapple Passion', 'Zooxo', 32);
insert into products (id, name, brand, price) values (617, 'Dc - Sakura Fu', 'Flashdog', 8);
insert into products (id, name, brand, price) values (618, 'Pepper - Pablano', 'Edgeblab', 58);
insert into products (id, name, brand, price) values (619, 'Mousse - Mango', 'Cogibox', 86);
insert into products (id, name, brand, price) values (620, 'Lettuce - Curly Endive', 'Browsebug', 30);
insert into products (id, name, brand, price) values (621, 'Wine - Duboeuf Beaujolais', 'Gevee', 79);
insert into products (id, name, brand, price) values (622, 'Turkey - Breast, Smoked', 'Feedbug', 65);
insert into products (id, name, brand, price) values (623, 'Lamb - Loin Chops', 'Tagopia', 13);
insert into products (id, name, brand, price) values (624, 'Dikon', 'Divavu', 100);
insert into products (id, name, brand, price) values (625, 'Container - Hngd Cll Blk 7x7x3', 'Topdrive', 82);
insert into products (id, name, brand, price) values (626, 'Bar Bran Honey Nut', 'Gabspot', 44);
insert into products (id, name, brand, price) values (627, 'Wine - Redchard Merritt', 'Blogtags', 12);
insert into products (id, name, brand, price) values (628, 'Water - Evian 355 Ml', 'Rhynoodle', 5);
insert into products (id, name, brand, price) values (629, 'Whmis Spray Bottle Graduated', 'Topicstorm', 38);
insert into products (id, name, brand, price) values (630, 'Soup - Campbellschix Stew', 'Divavu', 30);
insert into products (id, name, brand, price) values (631, 'Garbage Bags - Black', 'Feednation', 19);
insert into products (id, name, brand, price) values (632, 'Towel Dispenser', 'Divanoodle', 79);
insert into products (id, name, brand, price) values (633, 'Pasta - Gnocchi, Potato', 'Skilith', 37);
insert into products (id, name, brand, price) values (634, 'Table Cloth 91x91 Colour', 'Youbridge', 13);
insert into products (id, name, brand, price) values (635, 'Cocoa Powder - Dutched', 'Photobug', 85);
insert into products (id, name, brand, price) values (636, 'Taro Root', 'Ailane', 21);
insert into products (id, name, brand, price) values (637, 'Triple Sec - Mcguinness', 'Camido', 94);
insert into products (id, name, brand, price) values (638, 'Burger Veggie', 'Centidel', 86);
insert into products (id, name, brand, price) values (639, 'Sword Pick Asst', 'Skalith', 93);
insert into products (id, name, brand, price) values (640, 'Wine - Two Oceans Cabernet', 'Meevee', 13);
insert into products (id, name, brand, price) values (641, 'Beef - Cooked, Corned', 'Meeveo', 12);
insert into products (id, name, brand, price) values (642, 'Crackers - Soda / Saltins', 'Flashpoint', 58);
insert into products (id, name, brand, price) values (643, 'Dikon', 'Trilia', 72);
insert into products (id, name, brand, price) values (644, 'Beef - Tenderloin Tails', 'Jabbersphere', 42);
insert into products (id, name, brand, price) values (645, 'Puree - Strawberry', 'Eimbee', 55);
insert into products (id, name, brand, price) values (646, 'Chicken - Base', 'Zoomlounge', 9);
insert into products (id, name, brand, price) values (647, 'Browning Caramel Glace', 'Zooveo', 78);
insert into products (id, name, brand, price) values (648, 'Avocado', 'Dabvine', 58);
insert into products (id, name, brand, price) values (649, 'Mcguinness - Blue Curacao', 'Avamm', 70);
insert into products (id, name, brand, price) values (650, 'Wine - White, Antinore Orvieto', 'Vinte', 1);
insert into products (id, name, brand, price) values (651, 'Spice - Chili Powder Mexican', 'Skivee', 10);
insert into products (id, name, brand, price) values (652, 'Butter Ripple - Phillips', 'Trudoo', 95);
insert into products (id, name, brand, price) values (653, 'Squeeze Bottle', 'Livetube', 36);
insert into products (id, name, brand, price) values (654, 'Appetizer - Asian Shrimp Roll', 'Oodoo', 72);
insert into products (id, name, brand, price) values (655, 'Bread - Rosemary Focaccia', 'Thoughtmix', 34);
insert into products (id, name, brand, price) values (656, 'Island Oasis - Wildberry', 'Dynabox', 28);
insert into products (id, name, brand, price) values (657, 'Muffin Mix - Blueberry', 'Skyndu', 95);
insert into products (id, name, brand, price) values (658, 'Wine - Toasted Head', 'Mynte', 5);
insert into products (id, name, brand, price) values (659, 'Vinegar - Sherry', 'Demizz', 92);
insert into products (id, name, brand, price) values (660, 'Fuji Apples', 'Roodel', 64);
insert into products (id, name, brand, price) values (661, 'Tea Leaves - Oolong', 'Kimia', 7);
insert into products (id, name, brand, price) values (662, 'Cheese - Cheddar, Mild', 'Jatri', 67);
insert into products (id, name, brand, price) values (663, 'Broom Handle', 'Myworks', 45);
insert into products (id, name, brand, price) values (664, 'Wine - Zinfandel California 2002', 'Skinte', 90);
insert into products (id, name, brand, price) values (665, 'Onions - Cippolini', 'Brainbox', 42);
insert into products (id, name, brand, price) values (666, 'Cheese Cloth No 60', 'Vinte', 65);
insert into products (id, name, brand, price) values (667, 'Scallops - 10/20', 'Skivee', 61);
insert into products (id, name, brand, price) values (668, 'Beans - Fine', 'Feedmix', 42);
insert into products (id, name, brand, price) values (669, 'Jolt Cola - Red Eye', 'Zoovu', 1);
insert into products (id, name, brand, price) values (670, 'Water - Perrier', 'Photojam', 52);
insert into products (id, name, brand, price) values (671, 'Duck - Breast', 'Bubblebox', 60);
insert into products (id, name, brand, price) values (672, 'Seabream Whole Farmed', 'Leenti', 25);
insert into products (id, name, brand, price) values (673, 'Trout - Rainbow, Frozen', 'Ailane', 75);
insert into products (id, name, brand, price) values (674, 'Chicken - White Meat With Tender', 'Pixope', 35);
insert into products (id, name, brand, price) values (675, 'Wine - White, Concha Y Toro', 'Pixoboo', 51);
insert into products (id, name, brand, price) values (676, 'Bag - Clear 7 Lb', 'Viva', 92);
insert into products (id, name, brand, price) values (677, 'Water - Spring 1.5lit', 'Tazzy', 11);
insert into products (id, name, brand, price) values (678, 'Asparagus - White, Canned', 'Thoughtsphere', 89);
insert into products (id, name, brand, price) values (679, 'Horseradish Root', 'Shufflebeat', 68);
insert into products (id, name, brand, price) values (680, 'Soup - Campbells Chicken', 'Quimm', 44);
insert into products (id, name, brand, price) values (681, 'Cocoa Powder - Natural', 'Muxo', 39);
insert into products (id, name, brand, price) values (682, 'Container - Clear 32 Oz', 'Tagchat', 98);
insert into products (id, name, brand, price) values (683, 'Flavouring - Raspberry', 'Chatterpoint', 64);
insert into products (id, name, brand, price) values (684, 'Bread - Sour Batard', 'Quire', 1);
insert into products (id, name, brand, price) values (685, 'Meldea Green Tea Liquor', 'Zoombeat', 15);
insert into products (id, name, brand, price) values (686, 'Lettuce - Belgian Endive', 'Npath', 37);
insert into products (id, name, brand, price) values (687, 'Water - Green Tea Refresher', 'DabZ', 14);
insert into products (id, name, brand, price) values (688, 'Beef - Tenderlion, Center Cut', 'Livefish', 57);
insert into products (id, name, brand, price) values (689, 'Cake - Night And Day Choclate', 'Zoomdog', 10);
insert into products (id, name, brand, price) values (690, 'Kiwano', 'Zoomcast', 28);
insert into products (id, name, brand, price) values (691, 'Wine - Redchard Merritt', 'Vimbo', 43);
insert into products (id, name, brand, price) values (692, 'Wine - Stoneliegh Sauvignon', 'Gabspot', 72);
insert into products (id, name, brand, price) values (693, 'Roe - Flying Fish', 'Tekfly', 48);
insert into products (id, name, brand, price) values (694, 'Daikon Radish', 'Browsedrive', 22);
insert into products (id, name, brand, price) values (695, 'Cinnamon Buns Sticky', 'Devpoint', 40);
insert into products (id, name, brand, price) values (696, 'Piping Jelly - All Colours', 'LiveZ', 43);
insert into products (id, name, brand, price) values (697, 'Vodka - Lemon, Absolut', 'Bubbletube', 73);
insert into products (id, name, brand, price) values (698, 'Cheese - Shred Cheddar / Mozza', 'Eabox', 54);
insert into products (id, name, brand, price) values (699, 'Pork Loin Cutlets', 'Skyba', 1);
insert into products (id, name, brand, price) values (700, 'Wine - Cotes Du Rhone', 'Oloo', 100);
insert into products (id, name, brand, price) values (701, 'Crab Brie In Phyllo', 'Devpoint', 55);
insert into products (id, name, brand, price) values (702, 'Cup - 6oz, Foam', 'Photofeed', 24);
insert into products (id, name, brand, price) values (703, 'Syrup - Chocolate', 'Viva', 22);
insert into products (id, name, brand, price) values (704, 'Tart Shells - Savory, 4', 'Innojam', 40);
insert into products (id, name, brand, price) values (705, 'Garlic - Elephant', 'Tagchat', 75);
insert into products (id, name, brand, price) values (706, 'Pepper - Roasted Red', 'Tagtune', 90);
insert into products (id, name, brand, price) values (707, 'Milk - Homo', 'Skimia', 31);
insert into products (id, name, brand, price) values (708, 'Wine - Sauvignon Blanc Oyster', 'Mycat', 14);
insert into products (id, name, brand, price) values (709, 'Halibut - Whole, Fresh', 'Browsezoom', 14);
insert into products (id, name, brand, price) values (710, 'Mushroom - Trumpet, Dry', 'Rooxo', 78);
insert into products (id, name, brand, price) values (711, 'Rappini - Andy Boy', 'Babbleblab', 68);
insert into products (id, name, brand, price) values (712, 'Bread - Hamburger Buns', 'Flipbug', 85);
insert into products (id, name, brand, price) values (713, 'Wine - White, Lindemans Bin 95', 'Edgeify', 62);
insert into products (id, name, brand, price) values (714, 'Cheese - Brie, Triple Creme', 'Mudo', 92);
insert into products (id, name, brand, price) values (715, 'Bread - Pumpernickle, Rounds', 'Oodoo', 34);
insert into products (id, name, brand, price) values (716, 'Phyllo Dough', 'Skiba', 19);
insert into products (id, name, brand, price) values (717, 'Wine - Penfolds Koonuga Hill', 'Flipstorm', 22);
insert into products (id, name, brand, price) values (718, 'Ham - Smoked, Bone - In', 'Skilith', 82);
insert into products (id, name, brand, price) values (719, 'Wine - Guy Sage Touraine', 'Zoonder', 8);
insert into products (id, name, brand, price) values (720, 'Lid Tray - 12in Dome', 'Tavu', 96);
insert into products (id, name, brand, price) values (721, 'Beef - Ox Tongue, Pickled', 'Roodel', 1);
insert into products (id, name, brand, price) values (722, 'Spinach - Frozen', 'Wikizz', 91);
insert into products (id, name, brand, price) values (723, 'Crush - Orange, 355ml', 'Bubblebox', 55);
insert into products (id, name, brand, price) values (724, 'Pork - Back, Short Cut, Boneless', 'Meetz', 30);
insert into products (id, name, brand, price) values (725, 'Beef - Tender Tips', 'Jaxspan', 16);
insert into products (id, name, brand, price) values (726, 'Yogurt - Cherry, 175 Gr', 'Meeveo', 77);
insert into products (id, name, brand, price) values (727, 'Pepper - Black, Crushed', 'Twimm', 36);
insert into products (id, name, brand, price) values (728, 'Chinese Foods - Thick Noodles', 'Quimm', 75);
insert into products (id, name, brand, price) values (729, 'Garlic - Elephant', 'Twitternation', 36);
insert into products (id, name, brand, price) values (730, 'Parasol Pick Stir Stick', 'Vipe', 26);
insert into products (id, name, brand, price) values (731, 'Juice - V8 Splash', 'Flipbug', 81);
insert into products (id, name, brand, price) values (732, 'Ecolab - Hobart Upr Prewash Arm', 'Buzzbean', 57);
insert into products (id, name, brand, price) values (733, 'Flour - Rye', 'Youfeed', 81);
insert into products (id, name, brand, price) values (734, 'Spring Roll Wrappers', 'Shuffletag', 66);
insert into products (id, name, brand, price) values (735, 'Bread - Petit Baguette', 'Pixoboo', 53);
insert into products (id, name, brand, price) values (736, 'Chips - Potato Jalapeno', 'Fivechat', 53);
insert into products (id, name, brand, price) values (737, 'Myers Planters Punch', 'Flashpoint', 6);
insert into products (id, name, brand, price) values (738, 'Sausage - Chorizo', 'Fiveclub', 83);
insert into products (id, name, brand, price) values (739, 'Soup - Campbells Beef Noodle', 'Plajo', 94);
insert into products (id, name, brand, price) values (740, 'Coffee - Irish Cream', 'Livetube', 85);
insert into products (id, name, brand, price) values (741, 'Milk - Condensed', 'Twitterbeat', 24);
insert into products (id, name, brand, price) values (742, 'Triple Sec - Mcguinness', 'Avamm', 15);
insert into products (id, name, brand, price) values (743, 'Beef - Tenderloin - Aa', 'Dabfeed', 23);
insert into products (id, name, brand, price) values (744, 'Wine - Segura Viudas Aria Brut', 'Avamba', 31);
insert into products (id, name, brand, price) values (745, 'Wine - Ej Gallo Sierra Valley', 'Eare', 16);
insert into products (id, name, brand, price) values (746, 'Bread - Wheat Baguette', 'Riffpath', 13);
insert into products (id, name, brand, price) values (747, 'Tortillas - Flour, 10', 'Jabberstorm', 84);
insert into products (id, name, brand, price) values (748, 'Extract - Rum', 'Zazio', 74);
insert into products (id, name, brand, price) values (749, 'Soup - Campbells, Classic Chix', 'Muxo', 7);
insert into products (id, name, brand, price) values (750, 'Beets - Pickled', 'Meevee', 89);
insert into products (id, name, brand, price) values (751, 'Veal - Slab Bacon', 'Leexo', 42);
insert into products (id, name, brand, price) values (752, 'Bagel - Ched Chs Presliced', 'Skyble', 20);
insert into products (id, name, brand, price) values (753, 'V8 - Vegetable Cocktail', 'Jabbersphere', 34);
insert into products (id, name, brand, price) values (754, 'Sprouts - Onion', 'Wordware', 61);
insert into products (id, name, brand, price) values (755, 'Oven Mitts 17 Inch', 'Meevee', 7);
insert into products (id, name, brand, price) values (756, 'Pear - Packum', 'Skilith', 63);
insert into products (id, name, brand, price) values (757, 'Uniform Linen Charge', 'Mybuzz', 80);
insert into products (id, name, brand, price) values (758, 'Crab - Dungeness, Whole', 'Youfeed', 44);
insert into products (id, name, brand, price) values (759, 'Samosa - Veg', 'Latz', 88);
insert into products (id, name, brand, price) values (760, 'Olives - Black, Pitted', 'Fatz', 94);
insert into products (id, name, brand, price) values (761, 'Nori Sea Weed', 'Zoomdog', 31);
insert into products (id, name, brand, price) values (762, 'Wine - Balbach Riverside', 'Brainbox', 15);
insert into products (id, name, brand, price) values (763, 'Flour - Corn, Fine', 'Tambee', 6);
insert into products (id, name, brand, price) values (764, 'Bread - Rolls, Rye', 'Youbridge', 82);
insert into products (id, name, brand, price) values (765, 'Lid - 16 Oz And 32 Oz', 'Tagfeed', 61);
insert into products (id, name, brand, price) values (766, 'Paper Towel Touchless', 'Fivechat', 68);
insert into products (id, name, brand, price) values (767, 'Bread - White, Unsliced', 'Buzzbean', 64);
insert into products (id, name, brand, price) values (768, 'Cheese Cheddar Processed', 'Flashspan', 56);
insert into products (id, name, brand, price) values (769, 'Ice Cream Bar - Oreo Cone', 'Quimm', 57);
insert into products (id, name, brand, price) values (770, 'Onions - Spanish', 'Youbridge', 48);
insert into products (id, name, brand, price) values (771, 'Sausage - Blood Pudding', 'Skinte', 97);
insert into products (id, name, brand, price) values (772, 'Roe - White Fish', 'Tavu', 65);
insert into products (id, name, brand, price) values (773, 'Broccoli - Fresh', 'Eire', 51);
insert into products (id, name, brand, price) values (774, 'Chutney Sauce', 'Livefish', 46);
insert into products (id, name, brand, price) values (775, 'Lamb - Ground', 'Blogspan', 48);
insert into products (id, name, brand, price) values (776, 'Beans - Black Bean, Dry', 'Quatz', 25);
insert into products (id, name, brand, price) values (777, 'Crab - Back Fin Meat, Canned', 'Jayo', 16);
insert into products (id, name, brand, price) values (778, 'Nantucket Pine Orangebanana', 'Twitternation', 82);
insert into products (id, name, brand, price) values (779, 'Pepsi - 600ml', 'Mudo', 3);
insert into products (id, name, brand, price) values (780, 'Cheese - Ricotta', 'Trilia', 47);
insert into products (id, name, brand, price) values (781, 'Ginger - Ground', 'Kwinu', 67);
insert into products (id, name, brand, price) values (782, 'Juice - Happy Planet', 'Trudeo', 79);
insert into products (id, name, brand, price) values (783, 'Flour - Masa De Harina Mexican', 'Devpulse', 20);
insert into products (id, name, brand, price) values (784, 'Sauce - Balsamic Viniagrette', 'Leexo', 8);
insert into products (id, name, brand, price) values (785, 'Worcestershire Sauce', 'Topiczoom', 53);
insert into products (id, name, brand, price) values (786, 'Lamb - Shoulder, Boneless', 'Quatz', 72);
insert into products (id, name, brand, price) values (787, 'Wine - Balbach Riverside', 'Cogidoo', 76);
insert into products (id, name, brand, price) values (788, 'Beef - Ground Lean Fresh', 'Tanoodle', 86);
insert into products (id, name, brand, price) values (789, 'Mushroom - Oyster, Fresh', 'Bubblebox', 93);
insert into products (id, name, brand, price) values (790, 'Cookie Trail Mix', 'Twimbo', 96);
insert into products (id, name, brand, price) values (791, 'Anchovy In Oil', 'Quatz', 44);
insert into products (id, name, brand, price) values (792, 'Pastry - Apple Muffins - Mini', 'Kamba', 53);
insert into products (id, name, brand, price) values (793, 'Truffle Cups - White Paper', 'Trilith', 9);
insert into products (id, name, brand, price) values (794, 'Hummus - Spread', 'Meedoo', 34);
insert into products (id, name, brand, price) values (795, 'Canadian Emmenthal', 'Eamia', 33);
insert into products (id, name, brand, price) values (796, 'Samosa - Veg', 'Twinte', 86);
insert into products (id, name, brand, price) values (797, 'Pecan Raisin - Tarts', 'Feedfish', 41);
insert into products (id, name, brand, price) values (798, 'Pasta - Detalini, White, Fresh', 'Linkbridge', 40);
insert into products (id, name, brand, price) values (799, 'Wine - White, Pinot Grigio', 'Vipe', 10);
insert into products (id, name, brand, price) values (800, 'Trueblue - Blueberry Cranberry', 'Gabtune', 74);
insert into products (id, name, brand, price) values (801, 'Pork - Back Ribs', 'Rhyzio', 57);
insert into products (id, name, brand, price) values (802, 'Tart Shells - Savory, 4', 'Bluejam', 97);
insert into products (id, name, brand, price) values (803, 'Kiwi Gold Zespri', 'Zoomlounge', 63);
insert into products (id, name, brand, price) values (804, 'Grapes - Black', 'Vidoo', 33);
insert into products (id, name, brand, price) values (805, 'Wine - White, Pinot Grigio', 'Feedmix', 24);
insert into products (id, name, brand, price) values (806, 'Cranberries - Fresh', 'Devbug', 68);
insert into products (id, name, brand, price) values (807, 'Ice Cream - Chocolate', 'Realpoint', 64);
insert into products (id, name, brand, price) values (808, 'Mushroom - Chanterelle, Dry', 'Cogibox', 94);
insert into products (id, name, brand, price) values (809, 'Cheese - Swiss Sliced', 'Realcube', 30);
insert into products (id, name, brand, price) values (810, 'Danishes - Mini Raspberry', 'Livepath', 50);
insert into products (id, name, brand, price) values (811, 'Chinese Foods - Plain Fried Rice', 'Zoozzy', 44);
insert into products (id, name, brand, price) values (812, 'Steampan - Half Size Shallow', 'Jabbersphere', 90);
insert into products (id, name, brand, price) values (813, 'Pasta - Fett Alfredo, Single Serve', 'Chatterbridge', 48);
insert into products (id, name, brand, price) values (814, 'Corn - Cream, Canned', 'Skiba', 30);
insert into products (id, name, brand, price) values (815, 'Lambcasing', 'Topdrive', 29);
insert into products (id, name, brand, price) values (816, 'Gelatine Powder', 'Pixope', 90);
insert into products (id, name, brand, price) values (817, 'Butter - Pod', 'Nlounge', 56);
insert into products (id, name, brand, price) values (818, 'Chinese Lemon Pork', 'Livefish', 93);
insert into products (id, name, brand, price) values (819, 'Icecream - Dibs', 'Youbridge', 62);
insert into products (id, name, brand, price) values (820, 'Okra', 'Dabfeed', 25);
insert into products (id, name, brand, price) values (821, 'Ranchero - Primerba, Paste', 'Chatterpoint', 87);
insert into products (id, name, brand, price) values (822, 'Flour - Fast / Rapid', 'BlogXS', 52);
insert into products (id, name, brand, price) values (823, 'Cookie Double Choco', 'Edgeify', 61);
insert into products (id, name, brand, price) values (824, 'Apple - Macintosh', 'Voonix', 71);
insert into products (id, name, brand, price) values (825, 'Lentils - Green Le Puy', 'Quinu', 38);
insert into products (id, name, brand, price) values (826, 'Soup - Knorr, Ministrone', 'Rhybox', 58);
insert into products (id, name, brand, price) values (827, 'Fiddlehead - Frozen', 'Muxo', 2);
insert into products (id, name, brand, price) values (828, 'Chicken - Base, Ultimate', 'Zoovu', 15);
insert into products (id, name, brand, price) values (829, 'Octopus - Baby, Cleaned', 'Tazz', 79);
insert into products (id, name, brand, price) values (830, 'Carbonated Water - Lemon Lime', 'Meetz', 17);
insert into products (id, name, brand, price) values (831, 'Nantucket Pine Orangebanana', 'Realcube', 71);
insert into products (id, name, brand, price) values (832, 'Table Cloth 53x69 White', 'Voonte', 47);
insert into products (id, name, brand, price) values (833, 'Bagel - Everything', 'Quire', 83);
insert into products (id, name, brand, price) values (834, 'Wine - White, Mosel Gold', 'Bubblemix', 19);
insert into products (id, name, brand, price) values (835, 'Wine - Dubouef Macon - Villages', 'Brightbean', 47);
insert into products (id, name, brand, price) values (836, 'Pepper - Roasted Red', 'Jabbercube', 53);
insert into products (id, name, brand, price) values (837, 'Crab - Blue, Frozen', 'Realcube', 25);
insert into products (id, name, brand, price) values (838, 'Kaffir Lime Leaves', 'Wordtune', 63);
insert into products (id, name, brand, price) values (839, 'General Purpose Trigger', 'Shufflebeat', 98);
insert into products (id, name, brand, price) values (840, 'Container - Foam Dixie 12 Oz', 'Yoveo', 21);
insert into products (id, name, brand, price) values (841, 'Soup Bowl Clear 8oz92008', 'Dabvine', 100);
insert into products (id, name, brand, price) values (842, 'Nantucket - 518ml', 'Skipstorm', 29);
insert into products (id, name, brand, price) values (843, 'Goat - Leg', 'Yombu', 7);
insert into products (id, name, brand, price) values (844, 'Wine - Red, Black Opal Shiraz', 'Dabjam', 15);
insert into products (id, name, brand, price) values (845, 'Wine - Placido Pinot Grigo', 'Jabberbean', 43);
insert into products (id, name, brand, price) values (846, 'Mix - Cappucino Cocktail', 'Youbridge', 74);
insert into products (id, name, brand, price) values (847, 'Club Soda - Schweppes, 355 Ml', 'Mydeo', 64);
insert into products (id, name, brand, price) values (848, 'Turnip - Mini', 'Gabcube', 68);
insert into products (id, name, brand, price) values (849, 'Juice - Pineapple, 48 Oz', 'Topicshots', 5);
insert into products (id, name, brand, price) values (850, 'Oil - Pumpkinseed', 'Wordpedia', 47);
insert into products (id, name, brand, price) values (851, 'Ham - Procutinni', 'InnoZ', 2);
insert into products (id, name, brand, price) values (852, 'Bouillion - Fish', 'Yamia', 86);
insert into products (id, name, brand, price) values (853, 'Arctic Char - Fillets', 'Divanoodle', 66);
insert into products (id, name, brand, price) values (854, 'Syrup - Chocolate', 'Avamm', 39);
insert into products (id, name, brand, price) values (855, 'Beer - Moosehead', 'Izio', 96);
insert into products (id, name, brand, price) values (856, 'Sauce - Black Current, Dry Mix', 'Skipfire', 22);
insert into products (id, name, brand, price) values (857, 'Long Island Ice Tea', 'DabZ', 61);
insert into products (id, name, brand, price) values (858, 'Milk - Chocolate 500ml', 'Livepath', 91);
insert into products (id, name, brand, price) values (859, 'Beer - Sleemans Cream Ale', 'Thoughtblab', 47);
insert into products (id, name, brand, price) values (860, 'Raspberries - Fresh', 'Linkbuzz', 96);
insert into products (id, name, brand, price) values (861, 'Jolt Cola - Red Eye', 'Fliptune', 99);
insert into products (id, name, brand, price) values (862, 'Mikes Hard Lemonade', 'Nlounge', 19);
insert into products (id, name, brand, price) values (863, 'Olives - Morracan Dired', 'Voonyx', 54);
insert into products (id, name, brand, price) values (864, 'Scallops - In Shell', 'Tekfly', 98);
insert into products (id, name, brand, price) values (865, 'Beef - Top Sirloin', 'Mita', 74);
insert into products (id, name, brand, price) values (866, 'Rice - Brown', 'Teklist', 62);
insert into products (id, name, brand, price) values (867, 'Lettuce - Lambs Mash', 'Brainsphere', 39);
insert into products (id, name, brand, price) values (868, 'Mousse - Mango', 'Blogpad', 24);
insert into products (id, name, brand, price) values (869, 'Lamb - Whole, Fresh', 'Izio', 64);
insert into products (id, name, brand, price) values (870, 'Truffle Cups - Brown', 'Avaveo', 60);
insert into products (id, name, brand, price) values (871, 'Beef - Tongue, Cooked', 'Meezzy', 10);
insert into products (id, name, brand, price) values (872, 'Mushroom - Shitake, Fresh', 'Lajo', 40);
insert into products (id, name, brand, price) values (873, 'Shrimp - Baby, Cold Water', 'Meetz', 83);
insert into products (id, name, brand, price) values (874, 'Beef - Eye Of Round', 'Thoughtblab', 78);
insert into products (id, name, brand, price) values (875, 'Pastry - Apple Muffins - Mini', 'Rhyloo', 69);
insert into products (id, name, brand, price) values (876, 'Juice - Mango', 'Dabtype', 100);
insert into products (id, name, brand, price) values (877, 'Cactus Pads', 'Meezzy', 50);
insert into products (id, name, brand, price) values (878, 'Wine - Pinot Grigio Collavini', 'Zoomzone', 77);
insert into products (id, name, brand, price) values (879, 'Beets - Pickled', 'Fiveclub', 63);
insert into products (id, name, brand, price) values (880, 'Cognac - Courvaisier', 'Meejo', 49);
insert into products (id, name, brand, price) values (881, 'Tomato Puree', 'Plajo', 74);
insert into products (id, name, brand, price) values (882, 'Beef - Bones, Marrow', 'Divavu', 40);
insert into products (id, name, brand, price) values (883, 'Oven Mitts 17 Inch', 'Fivebridge', 81);
insert into products (id, name, brand, price) values (884, 'Bread - French Baquette', 'Einti', 40);
insert into products (id, name, brand, price) values (885, 'Lumpfish Black', 'Jayo', 96);
insert into products (id, name, brand, price) values (886, 'Pan Grease', 'Trilith', 99);
insert into products (id, name, brand, price) values (887, 'Muffin Mix - Morning Glory', 'Npath', 31);
insert into products (id, name, brand, price) values (888, 'Shrimp - Tiger 21/25', 'Bubblebox', 85);
insert into products (id, name, brand, price) values (889, 'Sprouts - Onion', 'Wikido', 38);
insert into products (id, name, brand, price) values (890, 'Salmon - Fillets', 'Janyx', 21);
insert into products (id, name, brand, price) values (891, 'Coffee Decaf Colombian', 'Skajo', 85);
insert into products (id, name, brand, price) values (892, 'Jam - Raspberry,jar', 'Feedbug', 32);
insert into products (id, name, brand, price) values (893, 'Capon - Whole', 'Devpulse', 26);
insert into products (id, name, brand, price) values (894, 'Croissant, Raw - Mini', 'Mita', 92);
insert into products (id, name, brand, price) values (895, 'Bread - Granary Small Pull', 'Tagfeed', 85);
insert into products (id, name, brand, price) values (896, 'Milk - Homo', 'Tagcat', 93);
insert into products (id, name, brand, price) values (897, 'Ocean Spray - Ruby Red', 'Jabbercube', 3);
insert into products (id, name, brand, price) values (898, 'Soup - Boston Clam Chowder', 'Livepath', 80);
insert into products (id, name, brand, price) values (899, 'Wine - Cotes Du Rhone', 'Camido', 27);
insert into products (id, name, brand, price) values (900, 'Carbonated Water - Wildberry', 'Gabtype', 76);
insert into products (id, name, brand, price) values (901, 'Apricots Fresh', 'Cogidoo', 18);
insert into products (id, name, brand, price) values (902, 'Sprouts - Alfalfa', 'Izio', 30);
insert into products (id, name, brand, price) values (903, 'Cheese - Shred Cheddar / Mozza', 'Gigabox', 24);
insert into products (id, name, brand, price) values (904, 'Spinach - Baby', 'Quinu', 9);
insert into products (id, name, brand, price) values (905, 'Asparagus - Green, Fresh', 'Jatri', 93);
insert into products (id, name, brand, price) values (906, 'Wooden Mop Handle', 'Lajo', 58);
insert into products (id, name, brand, price) values (907, 'Flour - So Mix Cake White', 'Kaymbo', 71);
insert into products (id, name, brand, price) values (908, 'Water - Spring Water, 355 Ml', 'Muxo', 89);
insert into products (id, name, brand, price) values (909, 'Dc - Sakura Fu', 'Twinte', 26);
insert into products (id, name, brand, price) values (910, 'Butter - Pod', 'Topiclounge', 33);
insert into products (id, name, brand, price) values (911, 'Lid - 10,12,16 Oz', 'Rooxo', 15);
insert into products (id, name, brand, price) values (912, 'Ice Cream Bar - Hageen Daz To', 'Kwinu', 30);
insert into products (id, name, brand, price) values (913, 'Egg - Salad Premix', 'Realcube', 30);
insert into products (id, name, brand, price) values (914, 'Cheese - Brie,danish', 'Vimbo', 73);
insert into products (id, name, brand, price) values (915, 'Oil - Hazelnut', 'Mynte', 62);
insert into products (id, name, brand, price) values (916, 'Beef Flat Iron Steak', 'Divape', 85);
insert into products (id, name, brand, price) values (917, 'Artichokes - Jerusalem', 'Twinder', 19);
insert into products (id, name, brand, price) values (918, 'Sausage - Chorizo', 'Buzzdog', 77);
insert into products (id, name, brand, price) values (919, 'Coffee - Irish Cream', 'Fanoodle', 74);
insert into products (id, name, brand, price) values (920, 'Bread Sour Rolls', 'Vitz', 95);
insert into products (id, name, brand, price) values (921, 'Tendrils - Baby Pea, Organic', 'Voonder', 5);
insert into products (id, name, brand, price) values (922, 'Sobe - Green Tea', 'Fatz', 22);
insert into products (id, name, brand, price) values (923, 'Shrimp - Black Tiger 16/20', 'Wikibox', 64);
insert into products (id, name, brand, price) values (924, 'Broom And Brush Rack Black', 'Demizz', 48);
insert into products (id, name, brand, price) values (925, 'Coriander - Ground', 'Feedbug', 79);
insert into products (id, name, brand, price) values (926, 'Pimento - Canned', 'Jaxspan', 79);
insert into products (id, name, brand, price) values (927, 'Sea Bass - Fillets', 'Photospace', 90);
insert into products (id, name, brand, price) values (928, 'Onions - White', 'Bluezoom', 75);
insert into products (id, name, brand, price) values (929, 'Pear - Packum', 'Babbleset', 95);
insert into products (id, name, brand, price) values (930, 'Duck - Legs', 'Oyope', 28);
insert into products (id, name, brand, price) values (931, 'Wine - Lamancha Do Crianza', 'Kayveo', 78);
insert into products (id, name, brand, price) values (932, 'Sprouts - Pea', 'Wikivu', 90);
insert into products (id, name, brand, price) values (933, 'Pepper - Orange', 'Voonder', 79);
insert into products (id, name, brand, price) values (934, 'Oil - Sesame', 'Shuffledrive', 42);
insert into products (id, name, brand, price) values (935, 'Thermometer Digital', 'Jetpulse', 71);
insert into products (id, name, brand, price) values (936, 'Dried Apple', 'Fliptune', 17);
insert into products (id, name, brand, price) values (937, 'Sugar - Palm', 'Pixonyx', 8);
insert into products (id, name, brand, price) values (938, 'Salmon - Whole, 4 - 6 Pounds', 'Voolith', 54);
insert into products (id, name, brand, price) values (939, 'Wine - Jafflin Bourgongone', 'Jaloo', 97);
insert into products (id, name, brand, price) values (940, 'Wine - Zonnebloem Pinotage', 'Tavu', 90);
insert into products (id, name, brand, price) values (941, 'Wine - Alicanca Vinho Verde', 'Realcube', 84);
insert into products (id, name, brand, price) values (942, 'Rice - Aborio', 'Wordtune', 20);
insert into products (id, name, brand, price) values (943, 'Skirt - 29 Foot', 'Zoozzy', 79);
insert into products (id, name, brand, price) values (944, 'Green Scrubbie Pad H.duty', 'Fatz', 17);
insert into products (id, name, brand, price) values (945, 'Cucumber - English', 'Gevee', 91);
insert into products (id, name, brand, price) values (946, 'Puree - Pear', 'Rhynoodle', 63);
insert into products (id, name, brand, price) values (947, 'Beef - Baby, Liver', 'Wikizz', 2);
insert into products (id, name, brand, price) values (948, 'Garbage Bags - Clear', 'Skyndu', 81);
insert into products (id, name, brand, price) values (949, 'Praline Paste', 'Flashspan', 89);
insert into products (id, name, brand, price) values (950, 'Ecolab - Orange Frc, Cleaner', 'Photobug', 75);
insert into products (id, name, brand, price) values (951, 'Chicken - Wings, Tip Off', 'Tagfeed', 70);
insert into products (id, name, brand, price) values (952, 'Table Cloth 81x81 White', 'Feednation', 80);
insert into products (id, name, brand, price) values (953, 'Chocolate - Milk', 'Skipfire', 88);
insert into products (id, name, brand, price) values (954, 'Lettuce - Treviso', 'Wikibox', 18);
insert into products (id, name, brand, price) values (955, 'Snapple Raspberry Tea', 'Kanoodle', 100);
insert into products (id, name, brand, price) values (956, 'Water - Spring Water 500ml', 'Centizu', 54);
insert into products (id, name, brand, price) values (957, 'Champagne - Brights, Dry', 'Voonyx', 91);
insert into products (id, name, brand, price) values (958, 'Brandy Apricot', 'Jamia', 97);
insert into products (id, name, brand, price) values (959, 'Beef - Striploin Aa', 'Feedspan', 98);
insert into products (id, name, brand, price) values (960, 'Saskatoon Berries - Frozen', 'Oyoyo', 50);
insert into products (id, name, brand, price) values (961, 'Bread - Sticks, Thin, Plain', 'Miboo', 76);
insert into products (id, name, brand, price) values (962, 'Salmon Steak - Cohoe 6 Oz', 'Centidel', 2);
insert into products (id, name, brand, price) values (963, 'Mustard - Individual Pkg', 'Agivu', 23);
insert into products (id, name, brand, price) values (964, 'Wine - Spumante Bambino White', 'Cogidoo', 86);
insert into products (id, name, brand, price) values (965, 'Soup Campbells Mexicali Tortilla', 'Photobug', 28);
insert into products (id, name, brand, price) values (966, 'Raspberries - Fresh', 'Skippad', 91);
insert into products (id, name, brand, price) values (967, 'Seaweed Green Sheets', 'Twitterbeat', 98);
insert into products (id, name, brand, price) values (968, 'Ginsing - Fresh', 'Gabvine', 10);
insert into products (id, name, brand, price) values (969, 'Table Cloth 91x91 Colour', 'Ainyx', 59);
insert into products (id, name, brand, price) values (970, 'Pepper - White, Whole', 'Kwinu', 97);
insert into products (id, name, brand, price) values (971, 'Potatoes - Fingerling 4 Oz', 'Ailane', 19);
insert into products (id, name, brand, price) values (972, 'Pepper - Chillies, Crushed', 'Mydo', 95);
insert into products (id, name, brand, price) values (973, 'Longos - Grilled Chicken With', 'Rhycero', 60);
insert into products (id, name, brand, price) values (974, 'Tortillas - Flour, 8', 'Voolith', 16);
insert into products (id, name, brand, price) values (975, 'Bacardi Breezer - Strawberry', 'Dynabox', 28);
insert into products (id, name, brand, price) values (976, 'Skirt - 24 Foot', 'Aimbo', 91);
insert into products (id, name, brand, price) values (977, 'Lettuce - Sea / Sea Asparagus', 'Jetwire', 59);
insert into products (id, name, brand, price) values (978, 'Pepper - Cayenne', 'Flashspan', 90);
insert into products (id, name, brand, price) values (979, 'Chinese Foods - Cantonese', 'Devcast', 62);
insert into products (id, name, brand, price) values (980, 'Cookies - Englishbay Wht', 'Trupe', 44);
insert into products (id, name, brand, price) values (981, 'Salmon - Atlantic, Skin On', 'Teklist', 18);
insert into products (id, name, brand, price) values (982, 'Langers - Mango Nectar', 'Trilia', 1);
insert into products (id, name, brand, price) values (983, 'Pork - Bacon,back Peameal', 'Jazzy', 92);
insert into products (id, name, brand, price) values (984, 'Ice Cream - Life Savers', 'Twiyo', 92);
insert into products (id, name, brand, price) values (985, 'Dates', 'Mita', 78);
insert into products (id, name, brand, price) values (986, 'Beef - Rib Roast, Capless', 'Youfeed', 35);
insert into products (id, name, brand, price) values (987, 'Rice - Long Grain', 'Linkbuzz', 80);
insert into products (id, name, brand, price) values (988, 'Cheese - Cheddar, Mild', 'Realcube', 13);
insert into products (id, name, brand, price) values (989, 'Wine - Barbera Alba Doc 2001', 'Quinu', 42);
insert into products (id, name, brand, price) values (990, 'Muffin Mix - Carrot', 'Tambee', 13);
insert into products (id, name, brand, price) values (991, 'Syrup - Chocolate', 'Yamia', 3);
insert into products (id, name, brand, price) values (992, 'Parsley Italian - Fresh', 'Gevee', 42);
insert into products (id, name, brand, price) values (993, 'Bacardi Breezer - Tropical', 'Kwinu', 75);
insert into products (id, name, brand, price) values (994, 'Wine - Shiraz Wolf Blass Premium', 'Skimia', 36);
insert into products (id, name, brand, price) values (995, 'Rice - Brown', 'Feedspan', 58);
insert into products (id, name, brand, price) values (996, 'Longos - Assorted Sandwich', 'Kwimbee', 36);
insert into products (id, name, brand, price) values (997, 'Sugar - Palm', 'Livetube', 63);
insert into products (id, name, brand, price) values (998, 'Pork - Ham Hocks - Smoked', 'Mynte', 14);
insert into products (id, name, brand, price) values (999, 'Pomegranates', 'Jabbersphere', 35);
insert into products (id, name, brand, price) values (1000, 'Spice - Peppercorn Melange', 'Oyope', 67);